<?php

use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Reset users table
        DB::table('districts')->truncate();

        // Init data
        $districts = [
            ['city_id' => 1, 'district_name' => 'Thành phố Long Xuyên'],
            ['city_id' => 1, 'district_name' => 'Thành phố Châu Đốc'],
            ['city_id' => 1, 'district_name' => 'Thị xã Tân Châu'],
            ['city_id' => 1, 'district_name' => 'Huyện An Phú'],
            ['city_id' => 1, 'district_name' => 'Huyện Châu Phú'],
            ['city_id' => 1, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 1, 'district_name' => 'Huyện Chợ Mới'],
            ['city_id' => 1, 'district_name' => 'Huyện Phú Tân'],
            ['city_id' => 1, 'district_name' => 'Huyện Thoại Sơn'],
            ['city_id' => 1, 'district_name' => 'Huyện Tịnh Biên'],
            ['city_id' => 1, 'district_name' => 'Huyện Tri Tôn'],
            ['city_id' => 2, 'district_name' => 'Thành phố Bà Rịa'],
            ['city_id' => 2, 'district_name' => 'Thành phố Vũng Tàu'],
            ['city_id' => 2, 'district_name' => 'Thị xã Phú Mỹ'],
            ['city_id' => 2, 'district_name' => 'Huyện Châu Đức'],
            ['city_id' => 2, 'district_name' => 'Huyện Côn Đảo'],
            ['city_id' => 2, 'district_name' => 'Huyện Đất Đỏ'],
            ['city_id' => 2, 'district_name' => 'Huyện Long Điền'],
            ['city_id' => 2, 'district_name' => 'Huyện Xuyên Mộc'],
            ['city_id' => 3, 'district_name' => 'Thành phố Bắc Giang'],
            ['city_id' => 3, 'district_name' => 'Huyện Hiệp Hòa'],
            ['city_id' => 3, 'district_name' => 'Huyện Yên Dũng'],
            ['city_id' => 3, 'district_name' => 'Huyện Lục Nam'],
            ['city_id' => 3, 'district_name' => 'Huyện Sơn Động'],
            ['city_id' => 3, 'district_name' => 'Huyện Lạng Giang'],
            ['city_id' => 3, 'district_name' => 'Huyện Việt Yên'],
            ['city_id' => 3, 'district_name' => 'Huyện Tân Yên'],
            ['city_id' => 3, 'district_name' => 'Huyện Lục Ngạn'],
            ['city_id' => 3, 'district_name' => 'Huyện Yên Thế'],
            ['city_id' => 4, 'district_name' => 'Thành phố Bắc Kạn'],
            ['city_id' => 4, 'district_name' => 'Huyện Huyện Ba Bể'],
            ['city_id' => 4, 'district_name' => 'Huyện Bạch Thông'],
            ['city_id' => 4, 'district_name' => 'Huyện Chợ Đồn'],
            ['city_id' => 4, 'district_name' => 'Huyện Chợ Mới'],
            ['city_id' => 4, 'district_name' => 'Huyện Na Rì'],
            ['city_id' => 4, 'district_name' => 'Huyện Ngân Sơn'],
            ['city_id' => 4, 'district_name' => 'Huyện Pác Nặm'],
            ['city_id' => 5, 'district_name' => 'Thành phố Bạc Liêu'],
            ['city_id' => 5, 'district_name' => 'Thị xã Giá Rai'],
            ['city_id' => 5, 'district_name' => 'Huyện Đông Hải'],
            ['city_id' => 5, 'district_name' => 'Huyện Hòa Bình'],
            ['city_id' => 5, 'district_name' => 'Huyện Hồng Dân'],
            ['city_id' => 5, 'district_name' => 'Huyện Phước Long'],
            ['city_id' => 5, 'district_name' => 'Vĩnh Lợi'],
            ['city_id' => 6, 'district_name' => 'Thành phố Bắc Ninh'],
            ['city_id' => 6, 'district_name' => 'Thị xã Từ Sơn'],
            ['city_id' => 6, 'district_name' => 'Huyện Gia Bình'],
            ['city_id' => 6, 'district_name' => 'Huyện Lương Tài'],
            ['city_id' => 6, 'district_name' => 'Huyện Quế Võ'],
            ['city_id' => 6, 'district_name' => 'Huyện Thuận Thành'],
            ['city_id' => 6, 'district_name' => 'Huyện Tiên Du'],
            ['city_id' => 6, 'district_name' => 'Huyện Yên Phong'],
            ['city_id' => 7, 'district_name' => 'Thành phố Bến Tre'],
            ['city_id' => 7, 'district_name' => 'Huyện Ba Tri'],
            ['city_id' => 7, 'district_name' => 'Huyện Bình Đại'],
            ['city_id' => 7, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 7, 'district_name' => 'Huyện Chợ Lách'],
            ['city_id' => 7, 'district_name' => 'Huyện Giồng Trôm'],
            ['city_id' => 7, 'district_name' => 'Huyện Mỏ Cày Bắc'],
            ['city_id' => 7, 'district_name' => 'Huyện Mỏ Cày Nam'],
            ['city_id' => 7, 'district_name' => 'Huyện Thạnh Phú'],
            ['city_id' => 8, 'district_name' => 'Thành phố Quy Nhơn'],
            ['city_id' => 8, 'district_name' => 'Thị xã An Nhơn'],
            ['city_id' => 8, 'district_name' => 'Huyện An Lão'],
            ['city_id' => 8, 'district_name' => 'Huyện Hoài Ân'],
            ['city_id' => 8, 'district_name' => 'Huyện Hoài Nhơn'],
            ['city_id' => 8, 'district_name' => 'Huyện Phù Cát'],
            ['city_id' => 8, 'district_name' => 'Huyện Phù Mỹ'],
            ['city_id' => 8, 'district_name' => 'Huyện Tây Sơn'],
            ['city_id' => 8, 'district_name' => 'Huyện Tuy Phước'],
            ['city_id' => 8, 'district_name' => 'Huyện Vân Canh'],
            ['city_id' => 8, 'district_name' => 'Huyện Vĩnh Thạnh'],
            ['city_id' => 9, 'district_name' => 'Thành phố Thủ Dầu Một'],
            ['city_id' => 9, 'district_name' => 'Thị xã Bến Cát'],
            ['city_id' => 9, 'district_name' => 'Thị xã Dĩ An'],
            ['city_id' => 9, 'district_name' => 'Thị xã Tân Uyên'],
            ['city_id' => 9, 'district_name' => 'Thị xã Thuận An'],
            ['city_id' => 9, 'district_name' => 'Huyện Bắc Tân Uyên'],
            ['city_id' => 9, 'district_name' => 'Huyện Bàu Bàng'],
            ['city_id' => 9, 'district_name' => 'Huyện Dầu Tiếng'],
            ['city_id' => 9, 'district_name' => 'Huyện Phú Giáo'],
            ['city_id' => 10, 'district_name' => 'Thành phố Đồng Xoài'],
            ['city_id' => 10, 'district_name' => 'Thị xã Bình Long'],
            ['city_id' => 10, 'district_name' => 'Thị xã Phước Long'],
            ['city_id' => 10, 'district_name' => 'Huyện Bù Đăng'],
            ['city_id' => 10, 'district_name' => 'Huyện Bù Đốp'],
            ['city_id' => 10, 'district_name' => 'Huyện Bù Gia Mập'],
            ['city_id' => 10, 'district_name' => 'Huyện Chơn Thành'],
            ['city_id' => 10, 'district_name' => 'Huyện Đồng Phú'],
            ['city_id' => 10, 'district_name' => 'Huyện Hớn Quản'],
            ['city_id' => 10, 'district_name' => 'Huyện Lộc Ninh'],
            ['city_id' => 10, 'district_name' => 'Huyện Phú Riềng'],
            ['city_id' => 11, 'district_name' => 'Thành phố Phan Thiết'],
            ['city_id' => 11, 'district_name' => 'Thị xã La Gi'],
            ['city_id' => 11, 'district_name' => 'Huyện Bắc Bình'],
            ['city_id' => 11, 'district_name' => 'Huyện Đức Linh'],
            ['city_id' => 11, 'district_name' => 'Huyện Hàm Tân'],
            ['city_id' => 11, 'district_name' => 'Huyện Hàm Thuận Bắc'],
            ['city_id' => 11, 'district_name' => 'Huyện Hàm Thuận Nam'],
            ['city_id' => 11, 'district_name' => 'Huyện Phú Quý'],
            ['city_id' => 11, 'district_name' => 'Huyện Tánh Linh'],
            ['city_id' => 11, 'district_name' => 'Huyện Tuy Phong'],
            ['city_id' => 12, 'district_name' => 'Thành phố Cà Mau'],
            ['city_id' => 12, 'district_name' => 'Huyện Cái Nước'],
            ['city_id' => 12, 'district_name' => 'Huyện Đầm Dơi'],
            ['city_id' => 12, 'district_name' => 'Huyện Năm Căn'],
            ['city_id' => 12, 'district_name' => 'Huyện Ngọc Hiển'],
            ['city_id' => 12, 'district_name' => 'Huyện Phú Tân'],
            ['city_id' => 12, 'district_name' => 'Huyện Thới Bình'],
            ['city_id' => 12, 'district_name' => 'Huyện Trần Văn Thời'],
            ['city_id' => 12, 'district_name' => 'Huyện U Minh'],
            ['city_id' => 13, 'district_name' => 'Thành phố Cao Bằng'],
            ['city_id' => 13, 'district_name' => 'Huyện Bảo Lạc'],
            ['city_id' => 13, 'district_name' => 'Huyện Bảo Lâm'],
            ['city_id' => 13, 'district_name' => 'Huyện Hạ Lang'],
            ['city_id' => 13, 'district_name' => 'Huyện Hà Quảng'],
            ['city_id' => 13, 'district_name' => 'Huyện Hòa An'],
            ['city_id' => 13, 'district_name' => 'Huyện Nguyên Bình'],
            ['city_id' => 13, 'district_name' => 'Huyện Phục Hòa'],
            ['city_id' => 13, 'district_name' => 'Huyện Quảng Uyên'],
            ['city_id' => 13, 'district_name' => 'Huyện Thạch An'],
            ['city_id' => 13, 'district_name' => 'Huyện Thông Nông'],
            ['city_id' => 13, 'district_name' => 'Huyện Trà Lĩnh'],
            ['city_id' => 13, 'district_name' => 'Huyện Trùng Khánh'],
            ['city_id' => 14, 'district_name' => 'Quận Bình Thủy'],
            ['city_id' => 14, 'district_name' => 'Quận Cái Răng'],
            ['city_id' => 14, 'district_name' => 'Quận Ninh Kiều'],
            ['city_id' => 14, 'district_name' => 'Quận Ô Môn'],
            ['city_id' => 14, 'district_name' => 'Quận Thốt Nốt'],
            ['city_id' => 14, 'district_name' => 'Huyện Huyện Cờ Đỏ'],
            ['city_id' => 14, 'district_name' => 'Phong Điền'],
            ['city_id' => 14, 'district_name' => 'Huyện Thới Lai'],
            ['city_id' => 14, 'district_name' => 'Huyện Vĩnh Thạnh'],
            ['city_id' => 15, 'district_name' => 'Quận Cẩm Lệ'],
            ['city_id' => 15, 'district_name' => 'Quận Hải Châu'],
            ['city_id' => 15, 'district_name' => 'Quận Liên Chiểu'],
            ['city_id' => 15, 'district_name' => 'Quận Ngũ Hành Sơn'],
            ['city_id' => 15, 'district_name' => 'Quận Sơn Trà'],
            ['city_id' => 15, 'district_name' => 'Quận Thanh Khê'],
            ['city_id' => 15, 'district_name' => 'Huyện Hòa Vang'],
            ['city_id' => 15, 'district_name' => 'Huyện Hoàng Sa'],
            ['city_id' => 16, 'district_name' => 'Thành phố Buôn Ma Thuột'],
            ['city_id' => 16, 'district_name' => 'Thị xã Buôn Hồ'],
            ['city_id' => 16, 'district_name' => 'Huyện Buôn Đôn'],
            ['city_id' => 16, 'district_name' => 'Huyện Cư Kuin'],
            ['city_id' => 16, 'district_name' => "Huyện Cư M'gar"],
            ['city_id' => 16, 'district_name' => "Huyện Ea H'leo"],
            ['city_id' => 16, 'district_name' => 'Huyện Ea Kar'],
            ['city_id' => 16, 'district_name' => 'Huyện Ea Súp'],
            ['city_id' => 16, 'district_name' => 'Huyện Krông Ana'],
            ['city_id' => 16, 'district_name' => 'Huyện Krông Bông'],
            ['city_id' => 16, 'district_name' => 'Huyện Krông Búk'],
            ['city_id' => 16, 'district_name' => 'Huyện Krông Năng'],
            ['city_id' => 16, 'district_name' => 'Huyện Krông Pắk'],
            ['city_id' => 16, 'district_name' => 'Huyện Lắk'],
            ['city_id' => 16, 'district_name' => "Huyện M'Đrắk"],
            ['city_id' => 17, 'district_name' => 'Thị xã Gia Nghĩa'],
            ['city_id' => 17, 'district_name' => 'Huyện Cư Jút'],
            ['city_id' => 17, 'district_name' => 'Huyện Đắk Glong'],
            ['city_id' => 17, 'district_name' => 'Huyện Đắk Mil'],
            ['city_id' => 17, 'district_name' => "Huyện Đắk R'lấp"],
            ['city_id' => 17, 'district_name' => 'Huyện Đắk Song'],
            ['city_id' => 17, 'district_name' => 'Huyện Krông Nô'],
            ['city_id' => 17, 'district_name' => 'Huyện Tuy Đức'],
            ['city_id' => 18, 'district_name' => 'Thành phố Điện Biên Phủ'],
            ['city_id' => 18, 'district_name' => 'Thị xã Mường Lay'],
            ['city_id' => 18, 'district_name' => 'Huyện Điện Biên'],
            ['city_id' => 18, 'district_name' => 'Huyện Điện Biên Đông'],
            ['city_id' => 18, 'district_name' => 'Huyện Mường Ảng'],
            ['city_id' => 18, 'district_name' => 'Huyện Mường Chà'],
            ['city_id' => 18, 'district_name' => 'Huyện Mường Nhé'],
            ['city_id' => 18, 'district_name' => 'Huyện Nậm Pồ'],
            ['city_id' => 18, 'district_name' => 'Huyện Tủa Chùa'],
            ['city_id' => 18, 'district_name' => 'Huyện Tuần Giáo'],
            ['city_id' => 19, 'district_name' => 'Thành phố Biên Hòa'],
            ['city_id' => 19, 'district_name' => 'Thị xã Long Khánh'],
            ['city_id' => 19, 'district_name' => 'Huyện Long Thành'],
            ['city_id' => 19, 'district_name' => 'Huyện Nhơn Trạch'],
            ['city_id' => 19, 'district_name' => 'Huyện Vĩnh Cửu'],
            ['city_id' => 19, 'district_name' => 'Huyện Trảng Bom'],
            ['city_id' => 19, 'district_name' => 'Huyện Thống Nhất'],
            ['city_id' => 19, 'district_name' => 'Huyện Cẩm Mỹ'],
            ['city_id' => 19, 'district_name' => 'Huyện Xuân Lộc'],
            ['city_id' => 19, 'district_name' => 'Huyện Định Quán'],
            ['city_id' => 19, 'district_name' => 'Huyện Tân Phú'],
            ['city_id' => 20, 'district_name' => 'Thành phố Cao Lãnh'],
            ['city_id' => 20, 'district_name' => 'Thành phố Sa Đéc'],
            ['city_id' => 20, 'district_name' => 'Thị Hồng Ngự'],
            ['city_id' => 20, 'district_name' => 'Huyện Cao Lãnh'],
            ['city_id' => 20, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 20, 'district_name' => 'Huyện Hồng Ngự'],
            ['city_id' => 20, 'district_name' => 'Huyện Lai Vung'],
            ['city_id' => 20, 'district_name' => 'Huyện Lấp Vò'],
            ['city_id' => 20, 'district_name' => 'Huyện Tam Nông'],
            ['city_id' => 20, 'district_name' => 'Huyện Tân Hồng'],
            ['city_id' => 20, 'district_name' => 'Huyện Huyện Thanh Bình'],
            ['city_id' => 20, 'district_name' => 'Huyện Tháp Mười'],
            ['city_id' => 21, 'district_name' => 'Thành phố Pleiku'],
            ['city_id' => 21, 'district_name' => 'Thị xã An Khê'],
            ['city_id' => 21, 'district_name' => 'Thị xã Ayun Pa'],
            ['city_id' => 21, 'district_name' => 'Huyện Chư Păh'],
            ['city_id' => 21, 'district_name' => 'Huyện Chư Prông'],
            ['city_id' => 21, 'district_name' => 'Huyện Chư Pưh'],
            ['city_id' => 21, 'district_name' => 'Huyện Chư Sê'],
            ['city_id' => 21, 'district_name' => 'Huyện Đắk Đoa'],
            ['city_id' => 21, 'district_name' => 'Huyện Đak Pơ'],
            ['city_id' => 21, 'district_name' => 'Huyện Đức Cơ'],
            ['city_id' => 21, 'district_name' => 'Huyện Ia Grai'],
            ['city_id' => 21, 'district_name' => 'Huyện Ia Pa'],
            ['city_id' => 21, 'district_name' => "Huyện K'Bang"],
            ['city_id' => 21, 'district_name' => 'Huyện Kông Chro'],
            ['city_id' => 21, 'district_name' => 'Huyện Krông Pa'],
            ['city_id' => 21, 'district_name' => 'Huyện Mang Yang'],
            ['city_id' => 21, 'district_name' => 'Huyện Phú Thiện'],
            ['city_id' => 22, 'district_name' => 'Thành phố Hà Giang'],
            ['city_id' => 22, 'district_name' => 'Huyện Bắc Mê'],
            ['city_id' => 22, 'district_name' => 'Huyện Bắc Quang'],
            ['city_id' => 22, 'district_name' => 'Huyện Đồng Văn'],
            ['city_id' => 22, 'district_name' => 'Huyện Hoàng Su Phì'],
            ['city_id' => 22, 'district_name' => 'Huyện Mèo Vạc'],
            ['city_id' => 22, 'district_name' => 'Huyện Quản Bạ'],
            ['city_id' => 22, 'district_name' => 'Huyện Quang Bình'],
            ['city_id' => 22, 'district_name' => 'Huyện Vị Xuyên'],
            ['city_id' => 22, 'district_name' => 'Huyện Xín Mần'],
            ['city_id' => 22, 'district_name' => 'Huyện Yên Minh'],
            ['city_id' => 23, 'district_name' => 'Thành phố Phủ Lý'],
            ['city_id' => 23, 'district_name' => 'Huyện Bình Lục'],
            ['city_id' => 23, 'district_name' => 'Huyện Duy Tiên'],
            ['city_id' => 23, 'district_name' => 'Huyện Kim Bảng'],
            ['city_id' => 23, 'district_name' => 'Huyện Lý Nhân'],
            ['city_id' => 23, 'district_name' => 'Huyện Thanh Liêm'],
            ['city_id' => 24, 'district_name' => 'Quận Ba Đình'],
            ['city_id' => 24, 'district_name' => 'Quận Bắc Từ Liêm'],
            ['city_id' => 24, 'district_name' => 'Quận Cầu Giấy'],
            ['city_id' => 24, 'district_name' => 'Quận Đống Đa'],
            ['city_id' => 24, 'district_name' => 'Quận Hà Đông'],
            ['city_id' => 24, 'district_name' => 'Quận Hai Bà Trưng'],
            ['city_id' => 24, 'district_name' => 'Quận Hoàn Kiếm'],
            ['city_id' => 24, 'district_name' => 'Quận Hoàng Mai'],
            ['city_id' => 24, 'district_name' => 'Quận Long Biên'],
            ['city_id' => 24, 'district_name' => 'Quận Nam Từ Liêm'],
            ['city_id' => 24, 'district_name' => 'Quận Tây Hồ'],
            ['city_id' => 24, 'district_name' => 'Quận Thanh Xuân'],
            ['city_id' => 24, 'district_name' => 'Thị xã Sơn Tây'],
            ['city_id' => 24, 'district_name' => 'Huyện Ba Vì'],
            ['city_id' => 24, 'district_name' => 'Huyện Chương Mỹ'],
            ['city_id' => 24, 'district_name' => 'Huyện Đan Phượng'],
            ['city_id' => 24, 'district_name' => 'Huyện Đông Anh'],
            ['city_id' => 24, 'district_name' => 'Huyện Gia Lâm'],
            ['city_id' => 24, 'district_name' => 'Huyện Hoài Đức'],
            ['city_id' => 24, 'district_name' => 'Huyện Mê Linh'],
            ['city_id' => 24, 'district_name' => 'Huyện Mỹ Đức'],
            ['city_id' => 24, 'district_name' => 'Huyện Phú Xuyên'],
            ['city_id' => 24, 'district_name' => 'Huyện Phúc Thọ'],
            ['city_id' => 24, 'district_name' => 'Huyện Quốc Oai'],
            ['city_id' => 24, 'district_name' => 'Huyện Sóc Sơn'],
            ['city_id' => 24, 'district_name' => 'Huyện Thạch Thất'],
            ['city_id' => 24, 'district_name' => 'Huyện Thanh Oai'],
            ['city_id' => 24, 'district_name' => 'Huyện Thanh Trì'],
            ['city_id' => 24, 'district_name' => 'Huyện Thường Tín'],
            ['city_id' => 24, 'district_name' => 'Huyện Ứng Hòa'],
            ['city_id' => 25, 'district_name' => 'Thành phố Hà Tĩnh'],
            ['city_id' => 25, 'district_name' => 'Thị xã Hồng Lĩnh'],
            ['city_id' => 25, 'district_name' => 'Thị xã Kỳ Anh'],
            ['city_id' => 25, 'district_name' => 'Huyện Cẩm Xuyên'],
            ['city_id' => 25, 'district_name' => 'Huyện Can Lộc'],
            ['city_id' => 25, 'district_name' => 'Huyện Đức Thọ'],
            ['city_id' => 25, 'district_name' => 'Huyện Hương Khê'],
            ['city_id' => 25, 'district_name' => 'Huyện Hương Sơn'],
            ['city_id' => 25, 'district_name' => 'Huyện Kỳ Anh'],
            ['city_id' => 25, 'district_name' => 'Huyện Lộc Hà'],
            ['city_id' => 25, 'district_name' => 'Huyện Nghi Xuân'],
            ['city_id' => 25, 'district_name' => 'Huyện Thạch Hà'],
            ['city_id' => 25, 'district_name' => 'Huyện Vũ Quang'],
            ['city_id' => 26, 'district_name' => 'Thành phố Hải Dương'],
            ['city_id' => 26, 'district_name' => 'Huyện Cẩm Giàng'],
            ['city_id' => 26, 'district_name' => 'Huyện Gia Lộc'],
            ['city_id' => 26, 'district_name' => 'Huyện Kim Thành'],
            ['city_id' => 26, 'district_name' => 'Huyện Kinh Môn'],
            ['city_id' => 26, 'district_name' => 'Huyện Nam Sách'],
            ['city_id' => 26, 'district_name' => 'Huyện Ninh Giang'],
            ['city_id' => 26, 'district_name' => 'Huyện Thanh Hà'],
            ['city_id' => 26, 'district_name' => 'Huyện Bình Giang'],
            ['city_id' => 26, 'district_name' => 'Huyện Chí Linh'],
            ['city_id' => 26, 'district_name' => 'Huyện Thanh Miện'],
            ['city_id' => 26, 'district_name' => 'Huyện Tứ Kỳ'],
            ['city_id' => 27, 'district_name' => 'Quận Đồ Sơn'],
            ['city_id' => 27, 'district_name' => 'Quận Dương Kinh'],
            ['city_id' => 27, 'district_name' => 'Quận Hải An'],
            ['city_id' => 27, 'district_name' => 'Quận Hồng Bàng'],
            ['city_id' => 27, 'district_name' => 'Quận Kiến An'],
            ['city_id' => 27, 'district_name' => 'Quận Lê Chân'],
            ['city_id' => 27, 'district_name' => 'Quận Ngô Quyền'],
            ['city_id' => 27, 'district_name' => 'Huyện An Dương'],
            ['city_id' => 27, 'district_name' => 'Huyện An Lão'],
            ['city_id' => 27, 'district_name' => 'Huyện Bạch Long Vĩ'],
            ['city_id' => 27, 'district_name' => 'Huyện Cát Hải'],
            ['city_id' => 27, 'district_name' => 'Huyện Kiến Thụy'],
            ['city_id' => 27, 'district_name' => 'Huyện Thủy Nguyên'],
            ['city_id' => 27, 'district_name' => 'Huyện Tiên Lãng'],
            ['city_id' => 27, 'district_name' => 'Huyện Vĩnh Bảo'],
            ['city_id' => 28, 'district_name' => 'Thành phố Vị Thanh'],
            ['city_id' => 28, 'district_name' => 'Thị xã Long Mỹ'],
            ['city_id' => 28, 'district_name' => 'Thị xã Ngã Bảy'],
            ['city_id' => 28, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 28, 'district_name' => 'Huyện Châu Thành A'],
            ['city_id' => 28, 'district_name' => 'Huyện Long Mỹ'],
            ['city_id' => 28, 'district_name' => 'Huyện Phụng Hiệp'],
            ['city_id' => 28, 'district_name' => 'Huyện Vị Thủy'],
            ['city_id' => 29, 'district_name' => 'Thành phố Hòa Bình'],
            ['city_id' => 29, 'district_name' => 'Huyện Cao Phong'],
            ['city_id' => 29, 'district_name' => 'Huyện Đà Bắc'],
            ['city_id' => 29, 'district_name' => 'Huyện Kim Bôi'],
            ['city_id' => 29, 'district_name' => 'Huyện Kỳ Sơn'],
            ['city_id' => 29, 'district_name' => 'Huyện Lạc Sơn'],
            ['city_id' => 29, 'district_name' => 'Huyện Lạc Thủy'],
            ['city_id' => 29, 'district_name' => 'Huyện Lương Sơn'],
            ['city_id' => 29, 'district_name' => 'Huyện Mai Châu'],
            ['city_id' => 29, 'district_name' => 'Huyện Tân Lạc'],
            ['city_id' => 29, 'district_name' => 'Huyện Yên Thủy'],
            ['city_id' => 30, 'district_name' => 'Thành phố Hưng Yên'],
            ['city_id' => 30, 'district_name' => 'Huyện Ân Thi'],
            ['city_id' => 30, 'district_name' => 'Huyện Khoái Châu'],
            ['city_id' => 30, 'district_name' => 'Huyện Kim Động'],
            ['city_id' => 30, 'district_name' => 'Huyện Mỹ Hào'],
            ['city_id' => 30, 'district_name' => 'Huyện Phù Cừ'],
            ['city_id' => 30, 'district_name' => 'Huyện Tiên Lữ'],
            ['city_id' => 30, 'district_name' => 'Huyện Văn Giang'],
            ['city_id' => 30, 'district_name' => 'Huyện Văn Lâm'],
            ['city_id' => 30, 'district_name' => 'Huyện Yên Mỹ'],
            ['city_id' => 31, 'district_name' => 'Thành phố Nha Trang'],
            ['city_id' => 31, 'district_name' => 'Thành phố Cam Ranh'],
            ['city_id' => 31, 'district_name' => 'Thị xã Ninh Hòa'],
            ['city_id' => 31, 'district_name' => 'Huyện Vạn Ninh'],
            ['city_id' => 31, 'district_name' => 'Huyện Diên Khánh'],
            ['city_id' => 31, 'district_name' => 'Huyện Khánh Sơn'],
            ['city_id' => 31, 'district_name' => 'Huyện Khánh Vĩnh'],
            ['city_id' => 31, 'district_name' => 'Huyện Cam Lâm'],
            ['city_id' => 31, 'district_name' => 'Huyện Trường Sa'],
            ['city_id' => 32, 'district_name' => 'Thành phố Rạch Giá'],
            ['city_id' => 32, 'district_name' => 'Thành phố Hà Tiên'],
            ['city_id' => 32, 'district_name' => 'Huyện An Biên'],
            ['city_id' => 32, 'district_name' => 'Huyện An Minh'],
            ['city_id' => 32, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 32, 'district_name' => 'Huyện Giang Thành'],
            ['city_id' => 32, 'district_name' => 'Huyện Giồng Riềng'],
            ['city_id' => 32, 'district_name' => 'Huyện Gò Quao'],
            ['city_id' => 32, 'district_name' => 'Huyện Hòn Đất'],
            ['city_id' => 32, 'district_name' => 'Huyện Kiên Hải'],
            ['city_id' => 32, 'district_name' => 'Huyện Kiên Lương'],
            ['city_id' => 32, 'district_name' => 'Huyện Phú Quốc'],
            ['city_id' => 32, 'district_name' => 'Huyện Tân Hiệp'],
            ['city_id' => 32, 'district_name' => 'Huyện U Minh Thượng'],
            ['city_id' => 32, 'district_name' => 'Huyện Vĩnh Thuận'],
            ['city_id' => 33, 'district_name' => 'Thành phố Kon Tum'],
            ['city_id' => 33, 'district_name' => 'Huyện Đăk Tô'],
            ['city_id' => 33, 'district_name' => 'Huyện Đăk Glei'],
            ['city_id' => 33, 'district_name' => 'Huyện Tu Mơ Rông'],
            ['city_id' => 33, 'district_name' => 'Huyện Kon Plông'],
            ['city_id' => 33, 'district_name' => 'Huyện Đăk Hà'],
            ['city_id' => 33, 'district_name' => 'Huyện Ngọc Hồi'],
            ['city_id' => 33, 'district_name' => 'Huyện Sa Thầy'],
            ['city_id' => 33, 'district_name' => 'Huyện Kon Rẫy'],
            ['city_id' => 33, 'district_name' => "Huyện Ia H'Drai"],
            ['city_id' => 34, 'district_name' => 'Thành phố Lai Châu'],
            ['city_id' => 34, 'district_name' => 'Huyện Mường Tè'],
            ['city_id' => 34, 'district_name' => 'Huyện Nậm Nhùn'],
            ['city_id' => 34, 'district_name' => 'Huyện Phong Thổ'],
            ['city_id' => 34, 'district_name' => 'Huyện Sìn Hồ'],
            ['city_id' => 34, 'district_name' => 'Huyện Tam Đường'],
            ['city_id' => 34, 'district_name' => 'Huyện Tân Uyên'],
            ['city_id' => 34, 'district_name' => 'Huyện Than Uyên'],
            ['city_id' => 35, 'district_name' => 'Thành phố Đà Lạt'],
            ['city_id' => 35, 'district_name' => 'Thành phố Bảo Lộc'],
            ['city_id' => 35, 'district_name' => 'Huyện Lạc Dương'],
            ['city_id' => 35, 'district_name' => 'Huyện Đơn Dương'],
            ['city_id' => 35, 'district_name' => 'Huyện Đức Trọng'],
            ['city_id' => 35, 'district_name' => 'Huyện Lâm Hà'],
            ['city_id' => 35, 'district_name' => 'Huyện Bảo Lâm'],
            ['city_id' => 35, 'district_name' => 'Huyện Di Linh'],
            ['city_id' => 35, 'district_name' => 'Huyện Đạ Huoai'],
            ['city_id' => 35, 'district_name' => 'Huyện Đạ Tẻh'],
            ['city_id' => 35, 'district_name' => 'Huyện Cát Tiên'],
            ['city_id' => 35, 'district_name' => 'Huyện Đam Rông'],
            ['city_id' => 36, 'district_name' => 'Thành phố Lạng Sơn'],
            ['city_id' => 36, 'district_name' => 'Huyện Cao Lộc'],
            ['city_id' => 36, 'district_name' => 'Huyện Bắc Sơn'],
            ['city_id' => 36, 'district_name' => 'Huyện Bình Gia'],
            ['city_id' => 36, 'district_name' => 'Huyện Chi Lăng'],
            ['city_id' => 36, 'district_name' => 'Huyện Đình Lập'],
            ['city_id' => 36, 'district_name' => 'Huyện Hữu Lũng'],
            ['city_id' => 36, 'district_name' => 'Huyện Lộc Bình'],
            ['city_id' => 36, 'district_name' => 'Huyện Tràng Định'],
            ['city_id' => 36, 'district_name' => 'Huyện Văn Lãng'],
            ['city_id' => 36, 'district_name' => 'Huyện Văn Quan'],
            ['city_id' => 37, 'district_name' => 'Thành phố Lào Cai'],
            ['city_id' => 37, 'district_name' => 'Huyện Bắc Hà'],
            ['city_id' => 37, 'district_name' => 'Huyện Bảo Thắng'],
            ['city_id' => 37, 'district_name' => 'Huyện Bảo Yên'],
            ['city_id' => 37, 'district_name' => 'Huyện Bát Xát'],
            ['city_id' => 37, 'district_name' => 'Huyện Mường Khương'],
            ['city_id' => 37, 'district_name' => 'Huyện Sa Pa'],
            ['city_id' => 37, 'district_name' => 'Huyện Si Ma Cai'],
            ['city_id' => 37, 'district_name' => 'Huyện Văn Bàn'],
            ['city_id' => 38, 'district_name' => 'Thành phố Tân An'],
            ['city_id' => 38, 'district_name' => 'Thị xã Kiến Tường'],
            ['city_id' => 38, 'district_name' => 'Huyện Bến Lức'],
            ['city_id' => 38, 'district_name' => 'Huyện Cần Đước'],
            ['city_id' => 38, 'district_name' => 'Huyện Cần Giuộc'],
            ['city_id' => 38, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 38, 'district_name' => 'Huyện Đức Hoà'],
            ['city_id' => 38, 'district_name' => 'Huyện Đức Huệ'],
            ['city_id' => 38, 'district_name' => 'Huyện Mộc Hoá'],
            ['city_id' => 38, 'district_name' => 'Huyện Tân Hưng'],
            ['city_id' => 38, 'district_name' => 'Huyện Tân Thạnh'],
            ['city_id' => 38, 'district_name' => 'Huyện Tân Trụ'],
            ['city_id' => 38, 'district_name' => 'Huyện Thạnh Hoá'],
            ['city_id' => 38, 'district_name' => 'Huyện Thủ Thừa'],
            ['city_id' => 38, 'district_name' => 'Huyện Vĩnh Hưng'],
            ['city_id' => 39, 'district_name' => 'Thành phố Nam Định'],
            ['city_id' => 39, 'district_name' => 'Huyện Giao Thủy'],
            ['city_id' => 39, 'district_name' => 'Huyện Hải Hậu'],
            ['city_id' => 39, 'district_name' => 'Huyện Mỹ Lộc'],
            ['city_id' => 39, 'district_name' => 'Huyện Nam Trực'],
            ['city_id' => 39, 'district_name' => 'Huyện Nghĩa Hưng'],
            ['city_id' => 39, 'district_name' => 'Huyện Trực Ninh'],
            ['city_id' => 39, 'district_name' => 'Huyện Vụ Bản'],
            ['city_id' => 39, 'district_name' => 'Huyện Xuân Trường'],
            ['city_id' => 39, 'district_name' => 'Huyện Ý Yên'],
            ['city_id' => 40, 'district_name' => 'Thành phố Vinh'],
            ['city_id' => 40, 'district_name' => 'Thị xã Cửa Lò'],
            ['city_id' => 40, 'district_name' => 'Thị xã Hoàng Mai'],
            ['city_id' => 40, 'district_name' => 'Thị xã Thái Hòa'],
            ['city_id' => 40, 'district_name' => 'Huyện Anh Sơn'],
            ['city_id' => 40, 'district_name' => 'Huyện Con Cuông'],
            ['city_id' => 40, 'district_name' => 'Huyện Diễn Châu'],
            ['city_id' => 40, 'district_name' => 'Huyện Đô Lương'],
            ['city_id' => 40, 'district_name' => 'Huyện Hưng Nguyên'],
            ['city_id' => 40, 'district_name' => 'Huyện Kỳ Sơn'],
            ['city_id' => 40, 'district_name' => 'Huyện Nam Đàn'],
            ['city_id' => 40, 'district_name' => 'Huyện Nghi Lộc'],
            ['city_id' => 40, 'district_name' => 'Huyện Nghĩa Đàn'],
            ['city_id' => 40, 'district_name' => 'Huyện Quế Phong'],
            ['city_id' => 40, 'district_name' => 'Huyện Quỳ Châu'],
            ['city_id' => 40, 'district_name' => 'Huyện Quỳ Hợp'],
            ['city_id' => 40, 'district_name' => 'Huyện Quỳnh Lưu'],
            ['city_id' => 40, 'district_name' => 'Huyện Tân Kỳ'],
            ['city_id' => 40, 'district_name' => 'Huyện Thanh Chương'],
            ['city_id' => 40, 'district_name' => 'Huyện Tương Dương'],
            ['city_id' => 40, 'district_name' => 'Huyện Yên Thành'],
            ['city_id' => 41, 'district_name' => 'Thành phố Ninh Bình'],
            ['city_id' => 41, 'district_name' => 'Thành phố Tam Điệp'],
            ['city_id' => 41, 'district_name' => 'Huyện Gia Viễn'],
            ['city_id' => 41, 'district_name' => 'Huyện Hoa Lư'],
            ['city_id' => 41, 'district_name' => 'Huyện Kim Sơn'],
            ['city_id' => 41, 'district_name' => 'Huyện Nho Quan'],
            ['city_id' => 41, 'district_name' => 'Huyện Yên Khánh'],
            ['city_id' => 41, 'district_name' => 'Huyện Yên Mô'],
            ['city_id' => 42, 'district_name' => 'Thành phố Phan Rang - Tháp Chàm'],
            ['city_id' => 42, 'district_name' => 'Huyện Bác Ái'],
            ['city_id' => 42, 'district_name' => 'Huyện Ninh Hải'],
            ['city_id' => 42, 'district_name' => 'Huyện Ninh Phước'],
            ['city_id' => 42, 'district_name' => 'Huyện Ninh Sơn'],
            ['city_id' => 42, 'district_name' => 'Huyện Thuận Bắc'],
            ['city_id' => 42, 'district_name' => 'Huyện Thuận Nam'],
            ['city_id' => 43, 'district_name' => 'Thành phố Việt Trì'],
            ['city_id' => 43, 'district_name' => 'Thị xã Phú Thọ'],
            ['city_id' => 43, 'district_name' => 'Huyện Cẩm Khê'],
            ['city_id' => 43, 'district_name' => 'Huyện Đoan Hùng'],
            ['city_id' => 43, 'district_name' => 'Huyện Hạ Hòa'],
            ['city_id' => 43, 'district_name' => 'Huyện Lâm Thao'],
            ['city_id' => 43, 'district_name' => 'Huyện Phù Ninh'],
            ['city_id' => 43, 'district_name' => 'Huyện Tam Nông'],
            ['city_id' => 43, 'district_name' => 'Huyện Tân Sơn'],
            ['city_id' => 43, 'district_name' => 'Huyện Thanh Ba'],
            ['city_id' => 43, 'district_name' => 'Huyện Thanh Sơn'],
            ['city_id' => 43, 'district_name' => 'Huyện Thanh Thủy'],
            ['city_id' => 43, 'district_name' => 'Huyện Yên Lập'],
            ['city_id' => 44, 'district_name' => 'Thành phố Đồng Hới'],
            ['city_id' => 44, 'district_name' => 'Thị xã Ba Đồn'],
            ['city_id' => 44, 'district_name' => 'Huyện Lệ Thủy'],
            ['city_id' => 44, 'district_name' => 'Huyện Quảng Ninh'],
            ['city_id' => 44, 'district_name' => 'Huyện Bố Trạch'],
            ['city_id' => 44, 'district_name' => 'Huyện Quảng Trạch'],
            ['city_id' => 44, 'district_name' => 'Huyện Tuyên Hóa'],
            ['city_id' => 44, 'district_name' => 'Huyện Minh Hóa'],
            ['city_id' => 45, 'district_name' => 'Thành phố Tam Kỳ'],
            ['city_id' => 45, 'district_name' => 'Thành phố Hội An'],
            ['city_id' => 45, 'district_name' => 'Thị xã Điện Bàn'],
            ['city_id' => 45, 'district_name' => 'Huyện Bắc Trà My'],
            ['city_id' => 45, 'district_name' => 'Huyện Đại Lộc'],
            ['city_id' => 45, 'district_name' => 'Huyện Đông Giang'],
            ['city_id' => 45, 'district_name' => 'Huyện Duy Xuyên'],
            ['city_id' => 45, 'district_name' => 'Huyện Hiệp Đức'],
            ['city_id' => 45, 'district_name' => 'Huyện Nam Giang'],
            ['city_id' => 45, 'district_name' => 'Huyện Nam Trà My'],
            ['city_id' => 45, 'district_name' => 'Huyện Nông Sơn'],
            ['city_id' => 45, 'district_name' => 'Huyện Núi Thành'],
            ['city_id' => 45, 'district_name' => 'Huyện Phú Ninh'],
            ['city_id' => 45, 'district_name' => 'Huyện Phước Sơn'],
            ['city_id' => 45, 'district_name' => 'Huyện Quế Sơn'],
            ['city_id' => 45, 'district_name' => 'Huyện Tây Giang'],
            ['city_id' => 45, 'district_name' => 'Huyện Thăng Bình'],
            ['city_id' => 45, 'district_name' => 'Huyện Tiên Phước'],
            ['city_id' => 46, 'district_name' => 'Thành phố Quảng Ngãi'],
            ['city_id' => 46, 'district_name' => 'Huyện Ba Tơ'],
            ['city_id' => 46, 'district_name' => 'Huyện Bình Sơn'],
            ['city_id' => 46, 'district_name' => 'Huyện Đức Phổ'],
            ['city_id' => 46, 'district_name' => 'Huyện Lý Sơn'],
            ['city_id' => 46, 'district_name' => 'Huyện Minh Long'],
            ['city_id' => 46, 'district_name' => 'Huyện Mộ Đức'],
            ['city_id' => 46, 'district_name' => 'Huyện Nghĩa Hành'],
            ['city_id' => 46, 'district_name' => 'Huyện Sơn Hà'],
            ['city_id' => 46, 'district_name' => 'Huyện Sơn Tây'],
            ['city_id' => 46, 'district_name' => 'Huyện Sơn Tịnh'],
            ['city_id' => 46, 'district_name' => 'Huyện Tây Trà'],
            ['city_id' => 46, 'district_name' => 'Huyện Trà Bồng'],
            ['city_id' => 46, 'district_name' => 'Huyện Tư Nghĩa'],
            ['city_id' => 47, 'district_name' => 'Thành phố Cẩm Phả'],
            ['city_id' => 47, 'district_name' => 'Thành phố Hạ Long'],
            ['city_id' => 47, 'district_name' => 'Thành phố Uông Bí'],
            ['city_id' => 47, 'district_name' => 'Thành phố Móng Cái'],
            ['city_id' => 47, 'district_name' => 'Thị xã Đông Triều'],
            ['city_id' => 47, 'district_name' => 'Thị xã Quảng Yên'],
            ['city_id' => 47, 'district_name' => 'Huyện Ba Chẽ'],
            ['city_id' => 47, 'district_name' => 'Huyện Bình Liêu'],
            ['city_id' => 47, 'district_name' => 'Huyện Cô Tô'],
            ['city_id' => 47, 'district_name' => 'Huyện Đầm Hà'],
            ['city_id' => 47, 'district_name' => 'Huyện Hải Hà'],
            ['city_id' => 47, 'district_name' => 'Huyện Hoành Bồ'],
            ['city_id' => 47, 'district_name' => 'Huyện Tiên Yên'],
            ['city_id' => 47, 'district_name' => 'Huyện Vân Đồn'],
            ['city_id' => 48, 'district_name' => 'Thành phố Đông Hà'],
            ['city_id' => 48, 'district_name' => 'Thị xã Quảng Trị'],
            ['city_id' => 48, 'district_name' => 'Huyện Cam Lộ'],
            ['city_id' => 48, 'district_name' => 'Huyện Cồn Cỏ'],
            ['city_id' => 48, 'district_name' => 'Huyện Đa Krông'],
            ['city_id' => 48, 'district_name' => 'Huyện Gio Linh'],
            ['city_id' => 48, 'district_name' => 'Huyện Hải Lăng'],
            ['city_id' => 48, 'district_name' => 'Huyện Hướng Hóa'],
            ['city_id' => 48, 'district_name' => 'Huyện Triệu Phong'],
            ['city_id' => 48, 'district_name' => 'Huyện Vĩnh Linh'],
            ['city_id' => 49, 'district_name' => 'Thành phố Sóc Trăng'],
            ['city_id' => 49, 'district_name' => 'Thành phố Ngã Năm'],
            ['city_id' => 49, 'district_name' => 'Thị xã Vĩnh Châu'],
            ['city_id' => 49, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 49, 'district_name' => 'Huyện Cù Lao Dung'],
            ['city_id' => 49, 'district_name' => 'Huyện Long Phú'],
            ['city_id' => 49, 'district_name' => 'Huyện Kế Sách'],
            ['city_id' => 49, 'district_name' => 'Huyện Mỹ Tú'],
            ['city_id' => 49, 'district_name' => 'Huyện Mỹ Xuyên'],
            ['city_id' => 49, 'district_name' => 'Huyện Thạnh Trị'],
            ['city_id' => 49, 'district_name' => 'Huyện Trần Đề'],
            ['city_id' => 50, 'district_name' => 'Thành phố Sơn La'],
            ['city_id' => 50, 'district_name' => 'Huyện Bắc Yên'],
            ['city_id' => 50, 'district_name' => 'Huyện Mai Sơn'],
            ['city_id' => 50, 'district_name' => 'Huyện Mộc Châu'],
            ['city_id' => 50, 'district_name' => 'Huyện Mường La'],
            ['city_id' => 50, 'district_name' => 'Huyện Phù Yên'],
            ['city_id' => 50, 'district_name' => 'Huyện Quỳnh Nhai'],
            ['city_id' => 50, 'district_name' => 'Huyện Sông Mã'],
            ['city_id' => 50, 'district_name' => 'Huyện Sốp Cộp'],
            ['city_id' => 50, 'district_name' => 'Huyện Thuận Châu'],
            ['city_id' => 50, 'district_name' => 'Huyện Vân Hồ'],
            ['city_id' => 50, 'district_name' => 'Huyện Yên Châu'],
            ['city_id' => 51, 'district_name' => 'Thành phố Tây Ninh'],
            ['city_id' => 51, 'district_name' => 'Huyện Bến Cầu'],
            ['city_id' => 51, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 51, 'district_name' => 'Huyện Dương Minh Châu'],
            ['city_id' => 51, 'district_name' => 'Huyện Gò Dầu'],
            ['city_id' => 51, 'district_name' => 'Huyện Hòa Thành'],
            ['city_id' => 51, 'district_name' => 'Huyện Tân Biên'],
            ['city_id' => 51, 'district_name' => 'Huyện Tân Châu'],
            ['city_id' => 51, 'district_name' => 'Huyện Trảng Bàng'],
            ['city_id' => 52, 'district_name' => 'Thành phố Thái Bình'],
            ['city_id' => 52, 'district_name' => 'Huyện Đông Hưng'],
            ['city_id' => 52, 'district_name' => 'Huyện Hưng Hà'],
            ['city_id' => 52, 'district_name' => 'Huyện Kiến Xương'],
            ['city_id' => 52, 'district_name' => 'Huyện Thái Thụy'],
            ['city_id' => 52, 'district_name' => 'Huyện Tiền Hải'],
            ['city_id' => 52, 'district_name' => 'Huyện Vũ Thư'],
            ['city_id' => 52, 'district_name' => 'Huyện Quỳnh Phụ'],
            ['city_id' => 53, 'district_name' => 'Thành phố Thái Nguyên'],
            ['city_id' => 53, 'district_name' => 'Thành phố Sông Công'],
            ['city_id' => 53, 'district_name' => 'Thị xã Phổ Yên'],
            ['city_id' => 53, 'district_name' => 'Huyện Đại Từ'],
            ['city_id' => 53, 'district_name' => 'Huyện Định Hóa'],
            ['city_id' => 53, 'district_name' => 'Huyện Đồng Hỷ'],
            ['city_id' => 53, 'district_name' => 'Huyện Phú Bình'],
            ['city_id' => 53, 'district_name' => 'Huyện Phú Lương'],
            ['city_id' => 53, 'district_name' => 'Huyện Võ Nhai'],
            ['city_id' => 54, 'district_name' => 'Thành phố Thanh Hóa'],
            ['city_id' => 54, 'district_name' => 'Thành phố Sầm Sơn'],
            ['city_id' => 54, 'district_name' => 'Thị xã Bỉm Sơn'],
            ['city_id' => 54, 'district_name' => 'Huyện Bá Thước'],
            ['city_id' => 54, 'district_name' => 'Huyện Cẩm Thủy'],
            ['city_id' => 54, 'district_name' => 'Huyện Đông Sơn'],
            ['city_id' => 54, 'district_name' => 'Huyện Hà Trung'],
            ['city_id' => 54, 'district_name' => 'Huyện Hậu Lộc'],
            ['city_id' => 54, 'district_name' => 'Huyện Hoằng Hóa'],
            ['city_id' => 54, 'district_name' => 'Huyện Lang Chánh'],
            ['city_id' => 54, 'district_name' => 'Huyện Mường Lát'],
            ['city_id' => 54, 'district_name' => 'Huyện Nga Sơn'],
            ['city_id' => 54, 'district_name' => 'Huyện Ngọc Lặc'],
            ['city_id' => 54, 'district_name' => 'Huyện Như Thanh'],
            ['city_id' => 54, 'district_name' => 'Huyện Như Xuân'],
            ['city_id' => 54, 'district_name' => 'Huyện Nông Cống'],
            ['city_id' => 54, 'district_name' => 'Huyện Quan Hóa'],
            ['city_id' => 54, 'district_name' => 'Huyện Quan Sơn'],
            ['city_id' => 54, 'district_name' => 'Huyện Quảng Xương'],
            ['city_id' => 54, 'district_name' => 'Huyện Thạch Thành'],
            ['city_id' => 54, 'district_name' => 'Huyện Thiệu Hóa'],
            ['city_id' => 54, 'district_name' => 'Huyện Thọ Xuân'],
            ['city_id' => 54, 'district_name' => 'Huyện Thường Xuân'],
            ['city_id' => 54, 'district_name' => 'Huyện Tĩnh Gia'],
            ['city_id' => 54, 'district_name' => 'Huyện Triệu Sơn'],
            ['city_id' => 54, 'district_name' => 'Huyện Vĩnh Lộc'],
            ['city_id' => 54, 'district_name' => 'Huyện Yên Định'],
            ['city_id' => 55, 'district_name' => 'Thành phố Huế'],
            ['city_id' => 55, 'district_name' => 'Thị xã Hương Thủy'],
            ['city_id' => 55, 'district_name' => 'Thị xã Hương Trà'],
            ['city_id' => 55, 'district_name' => 'Huyện A Lưới'],
            ['city_id' => 55, 'district_name' => 'Huyện Nam Đông'],
            ['city_id' => 55, 'district_name' => 'Huyện Phong Điền'],
            ['city_id' => 55, 'district_name' => 'Huyện Phú Lộc'],
            ['city_id' => 55, 'district_name' => 'Huyện Phú Vang'],
            ['city_id' => 55, 'district_name' => 'Huyện Quảng Điền'],
            ['city_id' => 56, 'district_name' => 'Thành phố Mỹ Tho'],
            ['city_id' => 56, 'district_name' => 'Thị xã Cai Lậy'],
            ['city_id' => 56, 'district_name' => 'Thị xã Gò Công'],
            ['city_id' => 56, 'district_name' => 'Huyện Cái Bè'],
            ['city_id' => 56, 'district_name' => 'Huyện Cai Lậy'],
            ['city_id' => 56, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 56, 'district_name' => 'Huyện Chợ Gạo'],
            ['city_id' => 56, 'district_name' => 'Huyện Gò Công Đông'],
            ['city_id' => 56, 'district_name' => 'Huyện Gò Công Tây'],
            ['city_id' => 56, 'district_name' => 'Huyện Tân Phú Đông'],
            ['city_id' => 56, 'district_name' => 'Huyện Tân Phước'],
            ['city_id' => 57, 'district_name' => 'Thành phố Trà Vinh'],
            ['city_id' => 57, 'district_name' => 'Thị xã Duyên Hải'],
            ['city_id' => 57, 'district_name' => 'Huyện Càng Long'],
            ['city_id' => 57, 'district_name' => 'Huyện Cầu Kè'],
            ['city_id' => 57, 'district_name' => 'Huyện Cầu Ngang'],
            ['city_id' => 57, 'district_name' => 'Huyện Châu Thành'],
            ['city_id' => 57, 'district_name' => 'Huyện Duyên Hải'],
            ['city_id' => 57, 'district_name' => 'Huyện Tiểu Cần'],
            ['city_id' => 57, 'district_name' => 'Huyện Trà Cú'],
            ['city_id' => 58, 'district_name' => 'Thành phố Tuyên Quang'],
            ['city_id' => 58, 'district_name' => 'Huyện hiêm Hóa'],
            ['city_id' => 58, 'district_name' => 'Huyện Hàm Yên'],
            ['city_id' => 58, 'district_name' => 'Huyện Lâm Bình'],
            ['city_id' => 58, 'district_name' => 'Huyện Na Hang'],
            ['city_id' => 58, 'district_name' => 'Huyện Sơn Dương'],
            ['city_id' => 58, 'district_name' => 'Huyện Yên Sơn'],
            ['city_id' => 59, 'district_name' => 'Quận 1'],
            ['city_id' => 59, 'district_name' => 'Quận 2'],
            ['city_id' => 59, 'district_name' => 'Quận 3'],
            ['city_id' => 59, 'district_name' => 'Quận 4'],
            ['city_id' => 59, 'district_name' => 'Quận 5'],
            ['city_id' => 59, 'district_name' => 'Quận 6'],
            ['city_id' => 59, 'district_name' => 'Quận 7'],
            ['city_id' => 59, 'district_name' => 'Quận 8'],
            ['city_id' => 59, 'district_name' => 'Quận 9'],
            ['city_id' => 59, 'district_name' => 'Quận 10'],
            ['city_id' => 59, 'district_name' => 'Quận 11'],
            ['city_id' => 59, 'district_name' => 'Quận 12'],
            ['city_id' => 59, 'district_name' => 'Quận Bình Tân'],
            ['city_id' => 59, 'district_name' => 'Quận Bình Thạnh'],
            ['city_id' => 59, 'district_name' => 'Quận Gò Vấp'],
            ['city_id' => 59, 'district_name' => 'Quận Phú Nhuận'],
            ['city_id' => 59, 'district_name' => 'Quận Tân Bình'],
            ['city_id' => 59, 'district_name' => 'Quận Tân Phú'],
            ['city_id' => 59, 'district_name' => 'Quận Thủ Đức'],
            ['city_id' => 59, 'district_name' => 'Huyện Bình Chánh'],
            ['city_id' => 59, 'district_name' => 'Huyện Cần Giờ'],
            ['city_id' => 59, 'district_name' => 'Huyện Củ Chi'],
            ['city_id' => 59, 'district_name' => 'Huyện Hóc Môn'],
            ['city_id' => 59, 'district_name' => 'Huyện Nhà Bè'],
            ['city_id' => 60, 'district_name' => 'Thành phố Vĩnh Long'],
            ['city_id' => 60, 'district_name' => 'Thị xã Bình Minh'],
            ['city_id' => 60, 'district_name' => 'Huyện Bình Tân'],
            ['city_id' => 60, 'district_name' => 'Huyện Long Hồ'],
            ['city_id' => 60, 'district_name' => 'Huyện Mang Thít'],
            ['city_id' => 60, 'district_name' => 'Huyện Tam Bình'],
            ['city_id' => 60, 'district_name' => 'Huyện Trà Ôn'],
            ['city_id' => 60, 'district_name' => 'Huyện Vũng Liêm'],
            ['city_id' => 61, 'district_name' => 'Thành phố Vĩnh Yên'],
            ['city_id' => 61, 'district_name' => 'Thành phố Phúc Yên'],
            ['city_id' => 61, 'district_name' => 'Huyện Bình Xuyên'],
            ['city_id' => 61, 'district_name' => 'Huyện Lập Thạch'],
            ['city_id' => 61, 'district_name' => 'Huyện Sông Lô'],
            ['city_id' => 61, 'district_name' => 'Huyện Tam Đảo'],
            ['city_id' => 61, 'district_name' => 'Huyện Tam Dương'],
            ['city_id' => 61, 'district_name' => 'Huyện Vĩnh Tường'],
            ['city_id' => 61, 'district_name' => 'Huyện Yên Lạc'],
            ['city_id' => 62, 'district_name' => 'Thành phố Yên Bái'],
            ['city_id' => 62, 'district_name' => 'Thị xã Nghĩa Lộ'],
            ['city_id' => 62, 'district_name' => 'Huyện Lục Yên'],
            ['city_id' => 62, 'district_name' => 'Huyện Mù Cang Chải'],
            ['city_id' => 62, 'district_name' => 'Huyện Huyện Trạm Tấu'],
            ['city_id' => 62, 'district_name' => 'Huyện Trấn Yên'],
            ['city_id' => 62, 'district_name' => 'Huyện Văn Chấn'],
            ['city_id' => 62, 'district_name' => 'Huyện Văn Yên'],
            ['city_id' => 62, 'district_name' => 'Huyện Yên Bình'],
            ['city_id' => 63, 'district_name' => 'Thành phố Tuy Hòa'],
            ['city_id' => 63, 'district_name' => 'Thị xã Sông Cầu'],
            ['city_id' => 63, 'district_name' => 'Huyện Đông Hòa'],
            ['city_id' => 63, 'district_name' => 'Huyện Đồng Xuân'],
            ['city_id' => 63, 'district_name' => 'Huyện Phú Hòa'],
            ['city_id' => 63, 'district_name' => 'Huyện Sơn Hòa'],
            ['city_id' => 63, 'district_name' => 'Huyện Sông Hinh'],
            ['city_id' => 63, 'district_name' => 'Huyện Tây Hòa'],
            ['city_id' => 63, 'district_name' => 'Huyện Tuy An'],
        ];

        // Insert DB
        DB::table('districts')->insert($districts);
    }
}
