<?php

use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Reset users table
        DB::table('districts')->truncate();

        // Init data
        $districts = [
            ['city_id' => 1, 'district_name' => 'TP. Long Xuyên'],
            ['city_id' => 1, 'district_name' => 'TP. Châu Đốc'],
            ['city_id' => 1, 'district_name' => 'TX. Tân Châu'],
            ['city_id' => 1, 'district_name' => 'An Phú'],
            ['city_id' => 1, 'district_name' => 'Châu Phú'],
            ['city_id' => 1, 'district_name' => 'Châu Thành'],
            ['city_id' => 1, 'district_name' => 'Chợ Mới'],
            ['city_id' => 1, 'district_name' => 'Phú Tân'],
            ['city_id' => 1, 'district_name' => 'Thoại Sơn'],
            ['city_id' => 1, 'district_name' => 'Tịnh Biên'],
            ['city_id' => 1, 'district_name' => 'Tri Tôn'],
            ['city_id' => 2, 'district_name' => 'TP. Bà Rịa'],
            ['city_id' => 2, 'district_name' => 'TP. Vũng Tàu'],
            ['city_id' => 2, 'district_name' => 'TX. Phú Mỹ'],
            ['city_id' => 2, 'district_name' => 'Châu Đức'],
            ['city_id' => 2, 'district_name' => 'Côn Đảo'],
            ['city_id' => 2, 'district_name' => 'Đất Đỏ'],
            ['city_id' => 2, 'district_name' => 'Long Điền'],
            ['city_id' => 2, 'district_name' => 'Xuyên Mộc'],
            ['city_id' => 3, 'district_name' => 'TP. Bắc Giang'],
            ['city_id' => 3, 'district_name' => 'Hiệp Hòa'],
            ['city_id' => 3, 'district_name' => 'Yên Dũng'],
            ['city_id' => 3, 'district_name' => 'Lục Nam'],
            ['city_id' => 3, 'district_name' => 'Sơn Động'],
            ['city_id' => 3, 'district_name' => 'Lạng Giang'],
            ['city_id' => 3, 'district_name' => 'Việt Yên'],
            ['city_id' => 3, 'district_name' => 'Tân Yên'],
            ['city_id' => 3, 'district_name' => 'Lục Ngạn'],
            ['city_id' => 3, 'district_name' => 'Yên Thế'],
            ['city_id' => 4, 'district_name' => 'TP. Bắc Kạn'],
            ['city_id' => 4, 'district_name' => 'Ba Bể'],
            ['city_id' => 4, 'district_name' => 'Bạch Thông'],
            ['city_id' => 4, 'district_name' => 'Chợ Đồn'],
            ['city_id' => 4, 'district_name' => 'Chợ Mới'],
            ['city_id' => 4, 'district_name' => 'Na Rì'],
            ['city_id' => 4, 'district_name' => 'Ngân Sơn'],
            ['city_id' => 4, 'district_name' => 'Pác Nặm'],
            ['city_id' => 5, 'district_name' => 'TP. Bạc Liêu'],
            ['city_id' => 5, 'district_name' => 'TX. Giá Rai'],
            ['city_id' => 5, 'district_name' => 'Đông Hải'],
            ['city_id' => 5, 'district_name' => 'Hòa Bình'],
            ['city_id' => 5, 'district_name' => 'Hồng Dân'],
            ['city_id' => 5, 'district_name' => 'Phước Long'],
            ['city_id' => 5, 'district_name' => 'Vĩnh Lợi'],
            ['city_id' => 6, 'district_name' => 'TP. Bắc Ninh'],
            ['city_id' => 6, 'district_name' => 'TX. Từ Sơn'],
            ['city_id' => 6, 'district_name' => 'Gia Bình'],
            ['city_id' => 6, 'district_name' => 'Lương Tài'],
            ['city_id' => 6, 'district_name' => 'Quế Võ'],
            ['city_id' => 6, 'district_name' => 'Thuận Thành'],
            ['city_id' => 6, 'district_name' => 'Tiên Du'],
            ['city_id' => 6, 'district_name' => 'Yên Phong'],
            ['city_id' => 7, 'district_name' => 'TP. Bến Tre'],
            ['city_id' => 7, 'district_name' => 'Ba Tri'],
            ['city_id' => 7, 'district_name' => 'Bình Đại'],
            ['city_id' => 7, 'district_name' => 'Châu Thành'],
            ['city_id' => 7, 'district_name' => 'Chợ Lách'],
            ['city_id' => 7, 'district_name' => 'Giồng Trôm'],
            ['city_id' => 7, 'district_name' => 'Mỏ Cày Bắc'],
            ['city_id' => 7, 'district_name' => 'Mỏ Cày Nam'],
            ['city_id' => 7, 'district_name' => 'Thạnh Phú'],
            ['city_id' => 8, 'district_name' => 'TP. Quy Nhơn'],
            ['city_id' => 8, 'district_name' => 'TX. An Nhơn'],
            ['city_id' => 8, 'district_name' => 'An Lão'],
            ['city_id' => 8, 'district_name' => 'Hoài Ân'],
            ['city_id' => 8, 'district_name' => 'Hoài Nhơn'],
            ['city_id' => 8, 'district_name' => 'Phù Cát'],
            ['city_id' => 8, 'district_name' => 'Phù Mỹ'],
            ['city_id' => 8, 'district_name' => 'Tây Sơn'],
            ['city_id' => 8, 'district_name' => 'Tuy Phước'],
            ['city_id' => 8, 'district_name' => 'Vân Canh'],
            ['city_id' => 8, 'district_name' => 'Vĩnh Thạnh'],
            ['city_id' => 9, 'district_name' => 'TP. Thủ Dầu Một'],
            ['city_id' => 9, 'district_name' => 'TX. Bến Cát'],
            ['city_id' => 9, 'district_name' => 'TX. Dĩ An'],
            ['city_id' => 9, 'district_name' => 'TX. Tân Uyên'],
            ['city_id' => 9, 'district_name' => 'TX. Thuận An'],
            ['city_id' => 9, 'district_name' => 'Bắc Tân Uyên'],
            ['city_id' => 9, 'district_name' => 'Bàu Bàng'],
            ['city_id' => 9, 'district_name' => 'Dầu Tiếng'],
            ['city_id' => 9, 'district_name' => 'Phú Giáo'],
            ['city_id' => 10, 'district_name' => 'TP. Đồng Xoài'],
            ['city_id' => 10, 'district_name' => 'TX. Bình Long'],
            ['city_id' => 10, 'district_name' => 'TX. Phước Long'],
            ['city_id' => 10, 'district_name' => 'Bù Đăng'],
            ['city_id' => 10, 'district_name' => 'Bù Đốp'],
            ['city_id' => 10, 'district_name' => 'Bù Gia Mập'],
            ['city_id' => 10, 'district_name' => 'Chơn Thành'],
            ['city_id' => 10, 'district_name' => 'Đồng Phú'],
            ['city_id' => 10, 'district_name' => 'Hớn Quản'],
            ['city_id' => 10, 'district_name' => 'Lộc Ninh'],
            ['city_id' => 10, 'district_name' => 'Phú Riềng'],
            ['city_id' => 11, 'district_name' => 'TP. Phan Thiết'],
            ['city_id' => 11, 'district_name' => 'TX. La Gi'],
            ['city_id' => 11, 'district_name' => 'Bắc Bình'],
            ['city_id' => 11, 'district_name' => 'Đức Linh'],
            ['city_id' => 11, 'district_name' => 'Hàm Tân'],
            ['city_id' => 11, 'district_name' => 'Hàm Thuận Bắc'],
            ['city_id' => 11, 'district_name' => 'Hàm Thuận Nam'],
            ['city_id' => 11, 'district_name' => 'Phú Quý'],
            ['city_id' => 11, 'district_name' => 'Tánh Linh'],
            ['city_id' => 11, 'district_name' => 'Tuy Phong'],
            ['city_id' => 12, 'district_name' => 'TP. Cà Mau'],
            ['city_id' => 12, 'district_name' => 'Cái Nước'],
            ['city_id' => 12, 'district_name' => 'Đầm Dơi'],
            ['city_id' => 12, 'district_name' => 'Năm Căn'],
            ['city_id' => 12, 'district_name' => 'Ngọc Hiển'],
            ['city_id' => 12, 'district_name' => 'Phú Tân'],
            ['city_id' => 12, 'district_name' => 'Thới Bình'],
            ['city_id' => 12, 'district_name' => 'Trần Văn Thời'],
            ['city_id' => 12, 'district_name' => 'U Minh'],
            ['city_id' => 13, 'district_name' => 'TP. Cao Bằng'],
            ['city_id' => 13, 'district_name' => 'Bảo Lạc'],
            ['city_id' => 13, 'district_name' => 'Bảo Lâm'],
            ['city_id' => 13, 'district_name' => 'Hạ Lang'],
            ['city_id' => 13, 'district_name' => 'Hà Quảng'],
            ['city_id' => 13, 'district_name' => 'Hòa An'],
            ['city_id' => 13, 'district_name' => 'Nguyên Bình'],
            ['city_id' => 13, 'district_name' => 'Phục Hòa'],
            ['city_id' => 13, 'district_name' => 'Quảng Uyên'],
            ['city_id' => 13, 'district_name' => 'Thạch An'],
            ['city_id' => 13, 'district_name' => 'Thông Nông'],
            ['city_id' => 13, 'district_name' => 'Trà Lĩnh'],
            ['city_id' => 13, 'district_name' => 'Trùng Khánh'],
            ['city_id' => 14, 'district_name' => 'Q. Bình Thủy'],
            ['city_id' => 14, 'district_name' => 'Q. Cái Răng'],
            ['city_id' => 14, 'district_name' => 'Q. Ninh Kiều'],
            ['city_id' => 14, 'district_name' => 'Q. Ô Môn'],
            ['city_id' => 14, 'district_name' => 'Q. Thốt Nốt'],
            ['city_id' => 14, 'district_name' => 'Cờ Đỏ'],
            ['city_id' => 14, 'district_name' => 'Phong Điền'],
            ['city_id' => 14, 'district_name' => 'Thới Lai'],
            ['city_id' => 14, 'district_name' => 'Vĩnh Thạnh'],
            ['city_id' => 15, 'district_name' => 'Q. Cẩm Lệ'],
            ['city_id' => 15, 'district_name' => 'Q. Hải Châu'],
            ['city_id' => 15, 'district_name' => 'Q. Liên Chiểu'],
            ['city_id' => 15, 'district_name' => 'Q. Ngũ Hành Sơn'],
            ['city_id' => 15, 'district_name' => 'Q. Sơn Trà'],
            ['city_id' => 15, 'district_name' => 'Q. Thanh Khê'],
            ['city_id' => 15, 'district_name' => 'Hòa Vang'],
            ['city_id' => 15, 'district_name' => 'Hoàng Sa'],
            ['city_id' => 16, 'district_name' => 'TP. Buôn Ma Thuột'],
            ['city_id' => 16, 'district_name' => 'TX. Buôn Hồ'],
            ['city_id' => 16, 'district_name' => 'Buôn Đôn'],
            ['city_id' => 16, 'district_name' => 'Cư Kuin'],
            ['city_id' => 16, 'district_name' => "Cư M'gar"],
            ['city_id' => 16, 'district_name' => "Ea H'leo"],
            ['city_id' => 16, 'district_name' => 'Ea Kar'],
            ['city_id' => 16, 'district_name' => 'Ea Súp'],
            ['city_id' => 16, 'district_name' => 'Krông Ana'],
            ['city_id' => 16, 'district_name' => 'Krông Bông'],
            ['city_id' => 16, 'district_name' => 'Krông Búk'],
            ['city_id' => 16, 'district_name' => 'Krông Năng'],
            ['city_id' => 16, 'district_name' => 'Krông Pắk'],
            ['city_id' => 16, 'district_name' => 'Lắk'],
            ['city_id' => 16, 'district_name' => "M'Đrắk"],
            ['city_id' => 17, 'district_name' => 'TX. Gia Nghĩa'],
            ['city_id' => 17, 'district_name' => 'Cư Jút'],
            ['city_id' => 17, 'district_name' => 'Đắk Glong'],
            ['city_id' => 17, 'district_name' => 'Đắk Mil'],
            ['city_id' => 17, 'district_name' => "Đắk R'lấp"],
            ['city_id' => 17, 'district_name' => 'Đắk Song'],
            ['city_id' => 17, 'district_name' => 'Krông Nô'],
            ['city_id' => 17, 'district_name' => 'Tuy Đức'],
            ['city_id' => 18, 'district_name' => 'TP. Điện Biên Phủ'],
            ['city_id' => 18, 'district_name' => 'TX. Mường Lay'],
            ['city_id' => 18, 'district_name' => 'Điện Biên'],
            ['city_id' => 18, 'district_name' => 'Điện Biên Đông'],
            ['city_id' => 18, 'district_name' => 'Mường Ảng'],
            ['city_id' => 18, 'district_name' => 'Mường Chà'],
            ['city_id' => 18, 'district_name' => 'Mường Nhé'],
            ['city_id' => 18, 'district_name' => 'Nậm Pồ'],
            ['city_id' => 18, 'district_name' => 'Tủa Chùa'],
            ['city_id' => 18, 'district_name' => 'Tuần Giáo'],
            ['city_id' => 19, 'district_name' => 'TP. Biên Hòa'],
            ['city_id' => 19, 'district_name' => 'TX. Long Khánh'],
            ['city_id' => 19, 'district_name' => 'Long Thành'],
            ['city_id' => 19, 'district_name' => 'Nhơn Trạch'],
            ['city_id' => 19, 'district_name' => 'Vĩnh Cửu'],
            ['city_id' => 19, 'district_name' => 'Trảng Bom'],
            ['city_id' => 19, 'district_name' => 'Thống Nhất'],
            ['city_id' => 19, 'district_name' => 'Cẩm Mỹ'],
            ['city_id' => 19, 'district_name' => 'Xuân Lộc'],
            ['city_id' => 19, 'district_name' => 'Định Quán'],
            ['city_id' => 19, 'district_name' => 'Tân Phú'],
            ['city_id' => 20, 'district_name' => 'TP. Cao Lãnh'],
            ['city_id' => 20, 'district_name' => 'TP. Sa Đéc'],
            ['city_id' => 20, 'district_name' => 'TX. Hồng Ngự'],
            ['city_id' => 20, 'district_name' => 'Cao Lãnh'],
            ['city_id' => 20, 'district_name' => 'Châu Thành'],
            ['city_id' => 20, 'district_name' => 'Hồng Ngự'],
            ['city_id' => 20, 'district_name' => 'Lai Vung'],
            ['city_id' => 20, 'district_name' => 'Lấp Vò'],
            ['city_id' => 20, 'district_name' => 'Tam Nông'],
            ['city_id' => 20, 'district_name' => 'Tân Hồng'],
            ['city_id' => 20, 'district_name' => 'Thanh Bình'],
            ['city_id' => 20, 'district_name' => 'Tháp Mười'],
            ['city_id' => 21, 'district_name' => 'TP. Pleiku'],
            ['city_id' => 21, 'district_name' => 'TX. An Khê'],
            ['city_id' => 21, 'district_name' => 'TX. Ayun Pa'],
            ['city_id' => 21, 'district_name' => 'Chư Păh'],
            ['city_id' => 21, 'district_name' => 'Chư Prông'],
            ['city_id' => 21, 'district_name' => 'Chư Pưh'],
            ['city_id' => 21, 'district_name' => 'Chư Sê'],
            ['city_id' => 21, 'district_name' => 'Đắk Đoa'],
            ['city_id' => 21, 'district_name' => 'Đak Pơ'],
            ['city_id' => 21, 'district_name' => 'Đức Cơ'],
            ['city_id' => 21, 'district_name' => 'Ia Grai'],
            ['city_id' => 21, 'district_name' => 'Ia Pa'],
            ['city_id' => 21, 'district_name' => "K'Bang"],
            ['city_id' => 21, 'district_name' => 'Kông Chro'],
            ['city_id' => 21, 'district_name' => 'Krông Pa'],
            ['city_id' => 21, 'district_name' => 'Mang Yang'],
            ['city_id' => 21, 'district_name' => 'Phú Thiện'],
            ['city_id' => 22, 'district_name' => 'TP. Hà Giang'],
            ['city_id' => 22, 'district_name' => 'Bắc Mê'],
            ['city_id' => 22, 'district_name' => 'Bắc Quang'],
            ['city_id' => 22, 'district_name' => 'Đồng Văn'],
            ['city_id' => 22, 'district_name' => 'Hoàng Su Phì'],
            ['city_id' => 22, 'district_name' => 'Mèo Vạc'],
            ['city_id' => 22, 'district_name' => 'Quản Bạ'],
            ['city_id' => 22, 'district_name' => 'Quang Bình'],
            ['city_id' => 22, 'district_name' => 'Vị Xuyên'],
            ['city_id' => 22, 'district_name' => 'Xín Mần'],
            ['city_id' => 22, 'district_name' => 'Yên Minh'],
            ['city_id' => 23, 'district_name' => 'TP. Phủ Lý'],
            ['city_id' => 23, 'district_name' => 'Bình Lục'],
            ['city_id' => 23, 'district_name' => 'Duy Tiên'],
            ['city_id' => 23, 'district_name' => 'Kim Bảng'],
            ['city_id' => 23, 'district_name' => 'Lý Nhân'],
            ['city_id' => 23, 'district_name' => 'Thanh Liêm'],
            ['city_id' => 24, 'district_name' => 'Q. Ba Đình'],
            ['city_id' => 24, 'district_name' => 'Q. Bắc Từ Liêm'],
            ['city_id' => 24, 'district_name' => 'Q. Cầu Giấy'],
            ['city_id' => 24, 'district_name' => 'Q. Đống Đa'],
            ['city_id' => 24, 'district_name' => 'Q. Hà Đông'],
            ['city_id' => 24, 'district_name' => 'Q. Hai Bà Trưng'],
            ['city_id' => 24, 'district_name' => 'Q. Hoàn Kiếm'],
            ['city_id' => 24, 'district_name' => 'Q. Hoàng Mai'],
            ['city_id' => 24, 'district_name' => 'Q. Long Biên'],
            ['city_id' => 24, 'district_name' => 'Q. Nam Từ Liêm'],
            ['city_id' => 24, 'district_name' => 'Q. Tây Hồ'],
            ['city_id' => 24, 'district_name' => 'Q. Thanh Xuân'],
            ['city_id' => 24, 'district_name' => 'TX. Sơn Tây'],
            ['city_id' => 24, 'district_name' => 'Ba Vì'],
            ['city_id' => 24, 'district_name' => 'Chương Mỹ'],
            ['city_id' => 24, 'district_name' => 'Đan Phượng'],
            ['city_id' => 24, 'district_name' => 'Đông Anh'],
            ['city_id' => 24, 'district_name' => 'Gia Lâm'],
            ['city_id' => 24, 'district_name' => 'Hoài Đức'],
            ['city_id' => 24, 'district_name' => 'Mê Linh'],
            ['city_id' => 24, 'district_name' => 'Mỹ Đức'],
            ['city_id' => 24, 'district_name' => 'Phú Xuyên'],
            ['city_id' => 24, 'district_name' => 'Phúc Thọ'],
            ['city_id' => 24, 'district_name' => 'Quốc Oai'],
            ['city_id' => 24, 'district_name' => 'Sóc Sơn'],
            ['city_id' => 24, 'district_name' => 'Thạch Thất'],
            ['city_id' => 24, 'district_name' => 'Thanh Oai'],
            ['city_id' => 24, 'district_name' => 'Thanh Trì'],
            ['city_id' => 24, 'district_name' => 'Thường Tín'],
            ['city_id' => 24, 'district_name' => 'Ứng Hòa'],
            ['city_id' => 25, 'district_name' => 'TP. Hà Tĩnh'],
            ['city_id' => 25, 'district_name' => 'TX. Hồng Lĩnh'],
            ['city_id' => 25, 'district_name' => 'TX. Kỳ Anh'],
            ['city_id' => 25, 'district_name' => 'Cẩm Xuyên'],
            ['city_id' => 25, 'district_name' => 'Can Lộc'],
            ['city_id' => 25, 'district_name' => 'Đức Thọ'],
            ['city_id' => 25, 'district_name' => 'Hương Khê'],
            ['city_id' => 25, 'district_name' => 'Hương Sơn'],
            ['city_id' => 25, 'district_name' => 'Kỳ Anh'],
            ['city_id' => 25, 'district_name' => 'Lộc Hà'],
            ['city_id' => 25, 'district_name' => 'Nghi Xuân'],
            ['city_id' => 25, 'district_name' => 'Thạch Hà'],
            ['city_id' => 25, 'district_name' => 'Vũ Quang'],
            ['city_id' => 26, 'district_name' => 'TP. Hải Dương'],
            ['city_id' => 26, 'district_name' => 'Cẩm Giàng'],
            ['city_id' => 26, 'district_name' => 'Gia Lộc'],
            ['city_id' => 26, 'district_name' => 'Kim Thành'],
            ['city_id' => 26, 'district_name' => 'Kinh Môn'],
            ['city_id' => 26, 'district_name' => 'Nam Sách'],
            ['city_id' => 26, 'district_name' => 'Ninh Giang'],
            ['city_id' => 26, 'district_name' => 'Thanh Hà'],
            ['city_id' => 26, 'district_name' => 'Bình Giang'],
            ['city_id' => 26, 'district_name' => 'Chí Linh'],
            ['city_id' => 26, 'district_name' => 'Thanh Miện'],
            ['city_id' => 26, 'district_name' => 'Tứ Kỳ'],
            ['city_id' => 27, 'district_name' => 'Q. Đồ Sơn'],
            ['city_id' => 27, 'district_name' => 'Q. Dương Kinh'],
            ['city_id' => 27, 'district_name' => 'Q. Hải An'],
            ['city_id' => 27, 'district_name' => 'Q. Hồng Bàng'],
            ['city_id' => 27, 'district_name' => 'Q. Kiến An'],
            ['city_id' => 27, 'district_name' => 'Q. Lê Chân'],
            ['city_id' => 27, 'district_name' => 'Q. Ngô Quyền'],
            ['city_id' => 27, 'district_name' => 'An Dương'],
            ['city_id' => 27, 'district_name' => 'An Lão'],
            ['city_id' => 27, 'district_name' => 'Bạch Long Vĩ'],
            ['city_id' => 27, 'district_name' => 'Cát Hải'],
            ['city_id' => 27, 'district_name' => 'Kiến Thụy'],
            ['city_id' => 27, 'district_name' => 'Thủy Nguyên'],
            ['city_id' => 27, 'district_name' => 'Tiên Lãng'],
            ['city_id' => 27, 'district_name' => 'Vĩnh Bảo'],
            ['city_id' => 28, 'district_name' => 'TP. Vị Thanh'],
            ['city_id' => 28, 'district_name' => 'TX. Long Mỹ'],
            ['city_id' => 28, 'district_name' => 'TX. Ngã Bảy'],
            ['city_id' => 28, 'district_name' => 'Châu Thành'],
            ['city_id' => 28, 'district_name' => 'Châu Thành A'],
            ['city_id' => 28, 'district_name' => 'Long Mỹ'],
            ['city_id' => 28, 'district_name' => 'Phụng Hiệp'],
            ['city_id' => 28, 'district_name' => 'Vị Thủy'],
            ['city_id' => 29, 'district_name' => 'TP. Hòa Bình'],
            ['city_id' => 29, 'district_name' => 'Cao Phong'],
            ['city_id' => 29, 'district_name' => 'Đà Bắc'],
            ['city_id' => 29, 'district_name' => 'Kim Bôi'],
            ['city_id' => 29, 'district_name' => 'Kỳ Sơn'],
            ['city_id' => 29, 'district_name' => 'Lạc Sơn'],
            ['city_id' => 29, 'district_name' => 'Lạc Thủy'],
            ['city_id' => 29, 'district_name' => 'Lương Sơn'],
            ['city_id' => 29, 'district_name' => 'Mai Châu'],
            ['city_id' => 29, 'district_name' => 'Tân Lạc'],
            ['city_id' => 29, 'district_name' => 'Yên Thủy'],
            ['city_id' => 30, 'district_name' => 'TP. Hưng Yên'],
            ['city_id' => 30, 'district_name' => 'Ân Thi'],
            ['city_id' => 30, 'district_name' => 'Khoái Châu'],
            ['city_id' => 30, 'district_name' => 'Kim Động'],
            ['city_id' => 30, 'district_name' => 'Mỹ Hào'],
            ['city_id' => 30, 'district_name' => 'Phù Cừ'],
            ['city_id' => 30, 'district_name' => 'Tiên Lữ'],
            ['city_id' => 30, 'district_name' => 'Văn Giang'],
            ['city_id' => 30, 'district_name' => 'Văn Lâm'],
            ['city_id' => 30, 'district_name' => 'Yên Mỹ'],
            ['city_id' => 31, 'district_name' => 'TP. Nha Trang'],
            ['city_id' => 31, 'district_name' => 'TP. Cam Ranh'],
            ['city_id' => 31, 'district_name' => 'TX. Ninh Hòa'],
            ['city_id' => 31, 'district_name' => 'Vạn Ninh'],
            ['city_id' => 31, 'district_name' => 'Diên Khánh'],
            ['city_id' => 31, 'district_name' => 'Khánh Sơn'],
            ['city_id' => 31, 'district_name' => 'Khánh Vĩnh'],
            ['city_id' => 31, 'district_name' => 'Cam Lâm'],
            ['city_id' => 31, 'district_name' => 'Trường Sa'],
            ['city_id' => 32, 'district_name' => 'TP. Rạch Giá'],
            ['city_id' => 32, 'district_name' => 'TP. Hà Tiên'],
            ['city_id' => 32, 'district_name' => 'An Biên'],
            ['city_id' => 32, 'district_name' => 'An Minh'],
            ['city_id' => 32, 'district_name' => 'Châu Thành'],
            ['city_id' => 32, 'district_name' => 'Giang Thành'],
            ['city_id' => 32, 'district_name' => 'Giồng Riềng'],
            ['city_id' => 32, 'district_name' => 'Gò Quao'],
            ['city_id' => 32, 'district_name' => 'Hòn Đất'],
            ['city_id' => 32, 'district_name' => 'Kiên Hải'],
            ['city_id' => 32, 'district_name' => 'Kiên Lương'],
            ['city_id' => 32, 'district_name' => 'Phú Quốc'],
            ['city_id' => 32, 'district_name' => 'Tân Hiệp'],
            ['city_id' => 32, 'district_name' => 'U Minh Thượng'],
            ['city_id' => 32, 'district_name' => 'Vĩnh Thuận'],
            ['city_id' => 33, 'district_name' => 'TP. Kon Tum'],
            ['city_id' => 33, 'district_name' => 'Đăk Tô'],
            ['city_id' => 33, 'district_name' => 'Đăk Glei'],
            ['city_id' => 33, 'district_name' => 'Tu Mơ Rông'],
            ['city_id' => 33, 'district_name' => 'Kon Plông'],
            ['city_id' => 33, 'district_name' => 'Đăk Hà'],
            ['city_id' => 33, 'district_name' => 'Ngọc Hồi'],
            ['city_id' => 33, 'district_name' => 'Sa Thầy'],
            ['city_id' => 33, 'district_name' => 'Kon Rẫy'],
            ['city_id' => 33, 'district_name' => "Ia H'Drai"],
            ['city_id' => 34, 'district_name' => 'TP. Lai Châu'],
            ['city_id' => 34, 'district_name' => 'Mường Tè'],
            ['city_id' => 34, 'district_name' => 'Nậm Nhùn'],
            ['city_id' => 34, 'district_name' => 'Phong Thổ'],
            ['city_id' => 34, 'district_name' => 'Sìn Hồ'],
            ['city_id' => 34, 'district_name' => 'Tam Đường'],
            ['city_id' => 34, 'district_name' => 'Tân Uyên'],
            ['city_id' => 34, 'district_name' => 'Than Uyên'],
            ['city_id' => 35, 'district_name' => 'TP. Đà Lạt'],
            ['city_id' => 35, 'district_name' => 'TP. Bảo Lộc'],
            ['city_id' => 35, 'district_name' => 'Lạc Dương'],
            ['city_id' => 35, 'district_name' => 'Đơn Dương'],
            ['city_id' => 35, 'district_name' => 'Đức Trọng'],
            ['city_id' => 35, 'district_name' => 'Lâm Hà'],
            ['city_id' => 35, 'district_name' => 'Bảo Lâm'],
            ['city_id' => 35, 'district_name' => 'Di Linh'],
            ['city_id' => 35, 'district_name' => 'Đạ Huoai'],
            ['city_id' => 35, 'district_name' => 'Đạ Tẻh'],
            ['city_id' => 35, 'district_name' => 'Cát Tiên'],
            ['city_id' => 35, 'district_name' => 'Đam Rông'],
            ['city_id' => 36, 'district_name' => 'TP. Lạng Sơn'],
            ['city_id' => 36, 'district_name' => 'Cao Lộc'],
            ['city_id' => 36, 'district_name' => 'Bắc Sơn'],
            ['city_id' => 36, 'district_name' => 'Bình Gia'],
            ['city_id' => 36, 'district_name' => 'Chi Lăng'],
            ['city_id' => 36, 'district_name' => 'Đình Lập'],
            ['city_id' => 36, 'district_name' => 'Hữu Lũng'],
            ['city_id' => 36, 'district_name' => 'Lộc Bình'],
            ['city_id' => 36, 'district_name' => 'Tràng Định'],
            ['city_id' => 36, 'district_name' => 'Văn Lãng'],
            ['city_id' => 36, 'district_name' => 'Văn Quan'],
            ['city_id' => 37, 'district_name' => 'TP. Lào Cai'],
            ['city_id' => 37, 'district_name' => 'Bắc Hà'],
            ['city_id' => 37, 'district_name' => 'Bảo Thắng'],
            ['city_id' => 37, 'district_name' => 'Bảo Yên'],
            ['city_id' => 37, 'district_name' => 'Bát Xát'],
            ['city_id' => 37, 'district_name' => 'Mường Khương'],
            ['city_id' => 37, 'district_name' => 'Sa Pa'],
            ['city_id' => 37, 'district_name' => 'Si Ma Cai'],
            ['city_id' => 37, 'district_name' => 'Văn Bàn'],
            ['city_id' => 38, 'district_name' => 'TP. Tân An'],
            ['city_id' => 38, 'district_name' => 'TX. Kiến Tường'],
            ['city_id' => 38, 'district_name' => 'Bến Lức'],
            ['city_id' => 38, 'district_name' => 'Cần Đước'],
            ['city_id' => 38, 'district_name' => 'Cần Giuộc'],
            ['city_id' => 38, 'district_name' => 'Châu Thành'],
            ['city_id' => 38, 'district_name' => 'Đức Hoà'],
            ['city_id' => 38, 'district_name' => 'Đức Huệ'],
            ['city_id' => 38, 'district_name' => 'Mộc Hoá'],
            ['city_id' => 38, 'district_name' => 'Tân Hưng'],
            ['city_id' => 38, 'district_name' => 'Tân Thạnh'],
            ['city_id' => 38, 'district_name' => 'Tân Trụ'],
            ['city_id' => 38, 'district_name' => 'Thạnh Hoá'],
            ['city_id' => 38, 'district_name' => 'Thủ Thừa'],
            ['city_id' => 38, 'district_name' => 'Vĩnh Hưng'],
            ['city_id' => 39, 'district_name' => 'TP. Nam Định'],
            ['city_id' => 39, 'district_name' => 'Giao Thủy'],
            ['city_id' => 39, 'district_name' => 'Hải Hậu'],
            ['city_id' => 39, 'district_name' => 'Mỹ Lộc'],
            ['city_id' => 39, 'district_name' => 'Nam Trực'],
            ['city_id' => 39, 'district_name' => 'Nghĩa Hưng'],
            ['city_id' => 39, 'district_name' => 'Trực Ninh'],
            ['city_id' => 39, 'district_name' => 'Vụ Bản'],
            ['city_id' => 39, 'district_name' => 'Xuân Trường'],
            ['city_id' => 39, 'district_name' => 'Ý Yên'],
            ['city_id' => 40, 'district_name' => 'TP. Vinh'],
            ['city_id' => 40, 'district_name' => 'TX. Cửa Lò'],
            ['city_id' => 40, 'district_name' => 'TX. Hoàng Mai'],
            ['city_id' => 40, 'district_name' => 'TX. Thái Hòa'],
            ['city_id' => 40, 'district_name' => 'Anh Sơn'],
            ['city_id' => 40, 'district_name' => 'Con Cuông'],
            ['city_id' => 40, 'district_name' => 'Diễn Châu'],
            ['city_id' => 40, 'district_name' => 'Đô Lương'],
            ['city_id' => 40, 'district_name' => 'Hưng Nguyên'],
            ['city_id' => 40, 'district_name' => 'Kỳ Sơn'],
            ['city_id' => 40, 'district_name' => 'Nam Đàn'],
            ['city_id' => 40, 'district_name' => 'Nghi Lộc'],
            ['city_id' => 40, 'district_name' => 'Nghĩa Đàn'],
            ['city_id' => 40, 'district_name' => 'Quế Phong'],
            ['city_id' => 40, 'district_name' => 'Quỳ Châu'],
            ['city_id' => 40, 'district_name' => 'Quỳ Hợp'],
            ['city_id' => 40, 'district_name' => 'Quỳnh Lưu'],
            ['city_id' => 40, 'district_name' => 'Tân Kỳ'],
            ['city_id' => 40, 'district_name' => 'Thanh Chương'],
            ['city_id' => 40, 'district_name' => 'Tương Dương'],
            ['city_id' => 40, 'district_name' => 'Yên Thành'],
            ['city_id' => 41, 'district_name' => 'TP. Ninh Bình'],
            ['city_id' => 41, 'district_name' => 'TP. Tam Điệp'],
            ['city_id' => 41, 'district_name' => 'Gia Viễn'],
            ['city_id' => 41, 'district_name' => 'Hoa Lư'],
            ['city_id' => 41, 'district_name' => 'Kim Sơn'],
            ['city_id' => 41, 'district_name' => 'Nho Quan'],
            ['city_id' => 41, 'district_name' => 'Yên Khánh'],
            ['city_id' => 41, 'district_name' => 'Yên Mô'],
            ['city_id' => 42, 'district_name' => 'TP. Phan Rang - Tháp Chàm'],
            ['city_id' => 42, 'district_name' => 'Bác Ái'],
            ['city_id' => 42, 'district_name' => 'Ninh Hải'],
            ['city_id' => 42, 'district_name' => 'Ninh Phước'],
            ['city_id' => 42, 'district_name' => 'Ninh Sơn'],
            ['city_id' => 42, 'district_name' => 'Thuận Bắc'],
            ['city_id' => 42, 'district_name' => 'Thuận Nam'],
            ['city_id' => 43, 'district_name' => 'TP. Việt Trì'],
            ['city_id' => 43, 'district_name' => 'TX. Phú Thọ'],
            ['city_id' => 43, 'district_name' => 'Cẩm Khê'],
            ['city_id' => 43, 'district_name' => 'Đoan Hùng'],
            ['city_id' => 43, 'district_name' => 'Hạ Hòa'],
            ['city_id' => 43, 'district_name' => 'Lâm Thao'],
            ['city_id' => 43, 'district_name' => 'Phù Ninh'],
            ['city_id' => 43, 'district_name' => 'Tam Nông'],
            ['city_id' => 43, 'district_name' => 'Tân Sơn'],
            ['city_id' => 43, 'district_name' => 'Thanh Ba'],
            ['city_id' => 43, 'district_name' => 'Thanh Sơn'],
            ['city_id' => 43, 'district_name' => 'Thanh Thủy'],
            ['city_id' => 43, 'district_name' => 'Yên Lập'],
            ['city_id' => 44, 'district_name' => 'TP. Đồng Hới'],
            ['city_id' => 44, 'district_name' => 'TX. Ba Đồn'],
            ['city_id' => 44, 'district_name' => 'Lệ Thủy'],
            ['city_id' => 44, 'district_name' => 'Quảng Ninh'],
            ['city_id' => 44, 'district_name' => 'Bố Trạch'],
            ['city_id' => 44, 'district_name' => 'Quảng Trạch'],
            ['city_id' => 44, 'district_name' => 'Tuyên Hóa'],
            ['city_id' => 44, 'district_name' => 'Minh Hóa'],
            ['city_id' => 45, 'district_name' => 'TP. Tam Kỳ'],
            ['city_id' => 45, 'district_name' => 'TP. Hội An'],
            ['city_id' => 45, 'district_name' => 'TX. Điện Bàn'],
            ['city_id' => 45, 'district_name' => 'Bắc Trà My'],
            ['city_id' => 45, 'district_name' => 'Đại Lộc'],
            ['city_id' => 45, 'district_name' => 'Đông Giang'],
            ['city_id' => 45, 'district_name' => 'Duy Xuyên'],
            ['city_id' => 45, 'district_name' => 'Hiệp Đức'],
            ['city_id' => 45, 'district_name' => 'Nam Giang'],
            ['city_id' => 45, 'district_name' => 'Nam Trà My'],
            ['city_id' => 45, 'district_name' => 'Nông Sơn'],
            ['city_id' => 45, 'district_name' => 'Núi Thành'],
            ['city_id' => 45, 'district_name' => 'Phú Ninh'],
            ['city_id' => 45, 'district_name' => 'Phước Sơn'],
            ['city_id' => 45, 'district_name' => 'Quế Sơn'],
            ['city_id' => 45, 'district_name' => 'Tây Giang'],
            ['city_id' => 45, 'district_name' => 'Thăng Bình'],
            ['city_id' => 45, 'district_name' => 'Tiên Phước'],
            ['city_id' => 46, 'district_name' => 'TP. Quảng Ngãi'],
            ['city_id' => 46, 'district_name' => 'Ba Tơ'],
            ['city_id' => 46, 'district_name' => 'Bình Sơn'],
            ['city_id' => 46, 'district_name' => 'Đức Phổ'],
            ['city_id' => 46, 'district_name' => 'Lý Sơn'],
            ['city_id' => 46, 'district_name' => 'Minh Long'],
            ['city_id' => 46, 'district_name' => 'Mộ Đức'],
            ['city_id' => 46, 'district_name' => 'Nghĩa Hành'],
            ['city_id' => 46, 'district_name' => 'Sơn Hà'],
            ['city_id' => 46, 'district_name' => 'Sơn Tây'],
            ['city_id' => 46, 'district_name' => 'Sơn Tịnh'],
            ['city_id' => 46, 'district_name' => 'Tây Trà'],
            ['city_id' => 46, 'district_name' => 'Trà Bồng'],
            ['city_id' => 46, 'district_name' => 'Tư Nghĩa'],
            ['city_id' => 47, 'district_name' => 'TP. Cẩm Phả'],
            ['city_id' => 47, 'district_name' => 'TP. Hạ Long'],
            ['city_id' => 47, 'district_name' => 'TP. Uông Bí'],
            ['city_id' => 47, 'district_name' => 'TP. Móng Cái'],
            ['city_id' => 47, 'district_name' => 'TX. Đông Triều'],
            ['city_id' => 47, 'district_name' => 'TX. Quảng Yên'],
            ['city_id' => 47, 'district_name' => 'Ba Chẽ'],
            ['city_id' => 47, 'district_name' => 'Bình Liêu'],
            ['city_id' => 47, 'district_name' => 'Cô Tô'],
            ['city_id' => 47, 'district_name' => 'Đầm Hà'],
            ['city_id' => 47, 'district_name' => 'Hải Hà'],
            ['city_id' => 47, 'district_name' => 'Hoành Bồ'],
            ['city_id' => 47, 'district_name' => 'Tiên Yên'],
            ['city_id' => 47, 'district_name' => 'Vân Đồn'],
            ['city_id' => 48, 'district_name' => 'TP. Đông Hà'],
            ['city_id' => 48, 'district_name' => 'TX. Quảng Trị'],
            ['city_id' => 48, 'district_name' => 'Cam Lộ'],
            ['city_id' => 48, 'district_name' => 'Cồn Cỏ'],
            ['city_id' => 48, 'district_name' => 'Đa Krông'],
            ['city_id' => 48, 'district_name' => 'Gio Linh'],
            ['city_id' => 48, 'district_name' => 'Hải Lăng'],
            ['city_id' => 48, 'district_name' => 'Hướng Hóa'],
            ['city_id' => 48, 'district_name' => 'Triệu Phong'],
            ['city_id' => 48, 'district_name' => 'Vĩnh Linh'],
            ['city_id' => 49, 'district_name' => 'TP. Sóc Trăng'],
            ['city_id' => 49, 'district_name' => 'TP. Ngã Năm'],
            ['city_id' => 49, 'district_name' => 'TX. Vĩnh Châu'],
            ['city_id' => 49, 'district_name' => 'Châu Thành'],
            ['city_id' => 49, 'district_name' => 'Cù Lao Dung'],
            ['city_id' => 49, 'district_name' => 'Long Phú'],
            ['city_id' => 49, 'district_name' => 'Kế Sách'],
            ['city_id' => 49, 'district_name' => 'Mỹ Tú'],
            ['city_id' => 49, 'district_name' => 'Mỹ Xuyên'],
            ['city_id' => 49, 'district_name' => 'Thạnh Trị'],
            ['city_id' => 49, 'district_name' => 'Trần Đề'],
            ['city_id' => 50, 'district_name' => 'TP. Sơn La'],
            ['city_id' => 50, 'district_name' => 'Bắc Yên'],
            ['city_id' => 50, 'district_name' => 'Mai Sơn'],
            ['city_id' => 50, 'district_name' => 'Mộc Châu'],
            ['city_id' => 50, 'district_name' => 'Mường La'],
            ['city_id' => 50, 'district_name' => 'Phù Yên'],
            ['city_id' => 50, 'district_name' => 'Quỳnh Nhai'],
            ['city_id' => 50, 'district_name' => 'Sông Mã'],
            ['city_id' => 50, 'district_name' => 'Sốp Cộp'],
            ['city_id' => 50, 'district_name' => 'Thuận Châu'],
            ['city_id' => 50, 'district_name' => 'Vân Hồ'],
            ['city_id' => 50, 'district_name' => 'Yên Châu'],
            ['city_id' => 51, 'district_name' => 'TP. Tây Ninh'],
            ['city_id' => 51, 'district_name' => 'Bến Cầu'],
            ['city_id' => 51, 'district_name' => 'Châu Thành'],
            ['city_id' => 51, 'district_name' => 'Dương Minh Châu'],
            ['city_id' => 51, 'district_name' => 'Gò Dầu'],
            ['city_id' => 51, 'district_name' => 'Hòa Thành'],
            ['city_id' => 51, 'district_name' => 'Tân Biên'],
            ['city_id' => 51, 'district_name' => 'Tân Châu'],
            ['city_id' => 51, 'district_name' => 'Trảng Bàng'],
            ['city_id' => 52, 'district_name' => 'TP. Thái Bình'],
            ['city_id' => 52, 'district_name' => 'Đông Hưng'],
            ['city_id' => 52, 'district_name' => 'Hưng Hà'],
            ['city_id' => 52, 'district_name' => 'Kiến Xương'],
            ['city_id' => 52, 'district_name' => 'Thái Thụy'],
            ['city_id' => 52, 'district_name' => 'Tiền Hải'],
            ['city_id' => 52, 'district_name' => 'Vũ Thư'],
            ['city_id' => 52, 'district_name' => 'Quỳnh Phụ'],
            ['city_id' => 53, 'district_name' => 'TP. Thái Nguyên'],
            ['city_id' => 53, 'district_name' => 'TP. Sông Công'],
            ['city_id' => 53, 'district_name' => 'TX. Phổ Yên'],
            ['city_id' => 53, 'district_name' => 'Đại Từ'],
            ['city_id' => 53, 'district_name' => 'Định Hóa'],
            ['city_id' => 53, 'district_name' => 'Đồng Hỷ'],
            ['city_id' => 53, 'district_name' => 'Phú Bình'],
            ['city_id' => 53, 'district_name' => 'Phú Lương'],
            ['city_id' => 53, 'district_name' => 'Võ Nhai'],
            ['city_id' => 54, 'district_name' => 'TP. Thanh Hóa'],
            ['city_id' => 54, 'district_name' => 'TP. Sầm Sơn'],
            ['city_id' => 54, 'district_name' => 'TX. Bỉm Sơn'],
            ['city_id' => 54, 'district_name' => 'Bá Thước'],
            ['city_id' => 54, 'district_name' => 'Cẩm Thủy'],
            ['city_id' => 54, 'district_name' => 'Đông Sơn'],
            ['city_id' => 54, 'district_name' => 'Hà Trung'],
            ['city_id' => 54, 'district_name' => 'Hậu Lộc'],
            ['city_id' => 54, 'district_name' => 'Hoằng Hóa'],
            ['city_id' => 54, 'district_name' => 'Lang Chánh'],
            ['city_id' => 54, 'district_name' => 'Mường Lát'],
            ['city_id' => 54, 'district_name' => 'Nga Sơn'],
            ['city_id' => 54, 'district_name' => 'Ngọc Lặc'],
            ['city_id' => 54, 'district_name' => 'Như Thanh'],
            ['city_id' => 54, 'district_name' => 'Như Xuân'],
            ['city_id' => 54, 'district_name' => 'Nông Cống'],
            ['city_id' => 54, 'district_name' => 'Quan Hóa'],
            ['city_id' => 54, 'district_name' => 'Quan Sơn'],
            ['city_id' => 54, 'district_name' => 'Quảng Xương'],
            ['city_id' => 54, 'district_name' => 'Thạch Thành'],
            ['city_id' => 54, 'district_name' => 'Thiệu Hóa'],
            ['city_id' => 54, 'district_name' => 'Thọ Xuân'],
            ['city_id' => 54, 'district_name' => 'Thường Xuân'],
            ['city_id' => 54, 'district_name' => 'Tĩnh Gia'],
            ['city_id' => 54, 'district_name' => 'Triệu Sơn'],
            ['city_id' => 54, 'district_name' => 'Vĩnh Lộc'],
            ['city_id' => 54, 'district_name' => 'Yên Định'],
            ['city_id' => 55, 'district_name' => 'TP. Huế'],
            ['city_id' => 55, 'district_name' => 'TX. Hương Thủy'],
            ['city_id' => 55, 'district_name' => 'TX. Hương Trà'],
            ['city_id' => 55, 'district_name' => 'A Lưới'],
            ['city_id' => 55, 'district_name' => 'Nam Đông'],
            ['city_id' => 55, 'district_name' => 'Phong Điền'],
            ['city_id' => 55, 'district_name' => 'Phú Lộc'],
            ['city_id' => 55, 'district_name' => 'Phú Vang'],
            ['city_id' => 55, 'district_name' => 'Quảng Điền'],
            ['city_id' => 56, 'district_name' => 'TP. Mỹ Tho'],
            ['city_id' => 56, 'district_name' => 'TX. Cai Lậy'],
            ['city_id' => 56, 'district_name' => 'TX. Gò Công'],
            ['city_id' => 56, 'district_name' => 'Cái Bè'],
            ['city_id' => 56, 'district_name' => 'Cai Lậy'],
            ['city_id' => 56, 'district_name' => 'Châu Thành'],
            ['city_id' => 56, 'district_name' => 'Chợ Gạo'],
            ['city_id' => 56, 'district_name' => 'Gò Công Đông'],
            ['city_id' => 56, 'district_name' => 'Gò Công Tây'],
            ['city_id' => 56, 'district_name' => 'Tân Phú Đông'],
            ['city_id' => 56, 'district_name' => 'Tân Phước'],
            ['city_id' => 57, 'district_name' => 'TP. Trà Vinh'],
            ['city_id' => 57, 'district_name' => 'TX. Duyên Hải'],
            ['city_id' => 57, 'district_name' => 'Càng Long'],
            ['city_id' => 57, 'district_name' => 'Cầu Kè'],
            ['city_id' => 57, 'district_name' => 'Cầu Ngang'],
            ['city_id' => 57, 'district_name' => 'Châu Thành'],
            ['city_id' => 57, 'district_name' => 'Duyên Hải'],
            ['city_id' => 57, 'district_name' => 'Tiểu Cần'],
            ['city_id' => 57, 'district_name' => 'Trà Cú'],
            ['city_id' => 58, 'district_name' => 'TP. Tuyên Quang'],
            ['city_id' => 58, 'district_name' => 'Chiêm Hóa'],
            ['city_id' => 58, 'district_name' => 'Hàm Yên'],
            ['city_id' => 58, 'district_name' => 'Lâm Bình'],
            ['city_id' => 58, 'district_name' => 'Na Hang'],
            ['city_id' => 58, 'district_name' => 'Sơn Dương'],
            ['city_id' => 58, 'district_name' => 'Yên Sơn'],
            ['city_id' => 59, 'district_name' => 'Q. 1'],
            ['city_id' => 59, 'district_name' => 'Q. 2'],
            ['city_id' => 59, 'district_name' => 'Q. 3'],
            ['city_id' => 59, 'district_name' => 'Q. 4'],
            ['city_id' => 59, 'district_name' => 'Q. 5'],
            ['city_id' => 59, 'district_name' => 'Q. 6'],
            ['city_id' => 59, 'district_name' => 'Q. 7'],
            ['city_id' => 59, 'district_name' => 'Q. 8'],
            ['city_id' => 59, 'district_name' => 'Q. 9'],
            ['city_id' => 59, 'district_name' => 'Q. 10'],
            ['city_id' => 59, 'district_name' => 'Q. 11'],
            ['city_id' => 59, 'district_name' => 'Q. 12'],
            ['city_id' => 59, 'district_name' => 'Q. Bình Tân'],
            ['city_id' => 59, 'district_name' => 'Q. Bình Thạnh'],
            ['city_id' => 59, 'district_name' => 'Q. Gò Vấp'],
            ['city_id' => 59, 'district_name' => 'Q. Phú Nhuận'],
            ['city_id' => 59, 'district_name' => 'Q. Tân Bình'],
            ['city_id' => 59, 'district_name' => 'Q. Tân Phú'],
            ['city_id' => 59, 'district_name' => 'Q. Thủ Đức'],
            ['city_id' => 59, 'district_name' => 'Bình Chánh'],
            ['city_id' => 59, 'district_name' => 'Cần Giờ'],
            ['city_id' => 59, 'district_name' => 'Củ Chi'],
            ['city_id' => 59, 'district_name' => 'Hóc Môn'],
            ['city_id' => 59, 'district_name' => 'Nhà Bè'],
            ['city_id' => 60, 'district_name' => 'TP. Vĩnh Long'],
            ['city_id' => 60, 'district_name' => 'TX. Bình Minh'],
            ['city_id' => 60, 'district_name' => 'Bình Tân'],
            ['city_id' => 60, 'district_name' => 'Long Hồ'],
            ['city_id' => 60, 'district_name' => 'Mang Thít'],
            ['city_id' => 60, 'district_name' => 'Tam Bình'],
            ['city_id' => 60, 'district_name' => 'Trà Ôn'],
            ['city_id' => 60, 'district_name' => 'Vũng Liêm'],
            ['city_id' => 61, 'district_name' => 'TP. Vĩnh Yên'],
            ['city_id' => 61, 'district_name' => 'TP. Phúc Yên'],
            ['city_id' => 61, 'district_name' => 'Bình Xuyên'],
            ['city_id' => 61, 'district_name' => 'Lập Thạch'],
            ['city_id' => 61, 'district_name' => 'Sông Lô'],
            ['city_id' => 61, 'district_name' => 'Tam Đảo'],
            ['city_id' => 61, 'district_name' => 'Tam Dương'],
            ['city_id' => 61, 'district_name' => 'Vĩnh Tường'],
            ['city_id' => 61, 'district_name' => 'Yên Lạc'],
            ['city_id' => 62, 'district_name' => 'TP. Yên Bái'],
            ['city_id' => 62, 'district_name' => 'TX. Nghĩa Lộ'],
            ['city_id' => 62, 'district_name' => 'Lục Yên'],
            ['city_id' => 62, 'district_name' => 'Mù Cang Chải'],
            ['city_id' => 62, 'district_name' => 'Trạm Tấu'],
            ['city_id' => 62, 'district_name' => 'Trấn Yên'],
            ['city_id' => 62, 'district_name' => 'Văn Chấn'],
            ['city_id' => 62, 'district_name' => 'Văn Yên'],
            ['city_id' => 62, 'district_name' => 'Yên Bình'],
            ['city_id' => 63, 'district_name' => 'TP. Tuy Hòa'],
            ['city_id' => 63, 'district_name' => 'TX. Sông Cầu'],
            ['city_id' => 63, 'district_name' => 'Đông Hòa'],
            ['city_id' => 63, 'district_name' => 'Đồng Xuân'],
            ['city_id' => 63, 'district_name' => 'Phú Hòa'],
            ['city_id' => 63, 'district_name' => 'Sơn Hòa'],
            ['city_id' => 63, 'district_name' => 'Sông Hinh'],
            ['city_id' => 63, 'district_name' => 'Tây Hòa'],
            ['city_id' => 63, 'district_name' => 'Tuy An'],
        ];

        // Insert DB
        DB::table('districts')->insert($districts);
    }
}
